// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annotations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnotation = `-- name: CreateAnnotation :one
INSERT INTO annotations (video_id, author_id, start_offset_sec, end_offset_sec, type, geometry, style, label)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, video_id, author_id, start_offset_sec, end_offset_sec, type, geometry, style, label, created_at
`

type CreateAnnotationParams struct {
	VideoID        pgtype.UUID
	AuthorID       pgtype.UUID
	StartOffsetSec float64
	EndOffsetSec   float64
	Type           AnnotationType
	Geometry       []byte
	Style          []byte
	Label          string
}

func (q *Queries) CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error) {
	row := q.db.QueryRow(ctx, createAnnotation,
		arg.VideoID,
		arg.AuthorID,
		arg.StartOffsetSec,
		arg.EndOffsetSec,
		arg.Type,
		arg.Geometry,
		arg.Style,
		arg.Label,
	)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.AuthorID,
		&i.StartOffsetSec,
		&i.EndOffsetSec,
		&i.Type,
		&i.Geometry,
		&i.Style,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnnotation = `-- name: DeleteAnnotation :execrows
DELETE FROM annotations WHERE id = $1
`

func (q *Queries) DeleteAnnotation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnotation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnnotation = `-- name: GetAnnotation :one
SELECT id, video_id, author_id, start_offset_sec, end_offset_sec, type, geometry, style, label, created_at FROM annotations WHERE id = $1
`

func (q *Queries) GetAnnotation(ctx context.Context, id pgtype.UUID) (Annotation, error) {
	row := q.db.QueryRow(ctx, getAnnotation, id)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.AuthorID,
		&i.StartOffsetSec,
		&i.EndOffsetSec,
		&i.Type,
		&i.Geometry,
		&i.Style,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const listAnnotationsByVideo = `-- name: ListAnnotationsByVideo :many
SELECT id, video_id, author_id, start_offset_sec, end_offset_sec, type, geometry, style, label, created_at
FROM annotations
WHERE video_id = $1
ORDER BY start_offset_sec ASC, id ASC
`

func (q *Queries) ListAnnotationsByVideo(ctx context.Context, videoID pgtype.UUID) ([]Annotation, error) {
	rows, err := q.db.Query(ctx, listAnnotationsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Annotation
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.AuthorID,
			&i.StartOffsetSec,
			&i.EndOffsetSec,
			&i.Type,
			&i.Geometry,
			&i.Style,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnotation = `-- name: UpdateAnnotation :one
UPDATE annotations
SET
  start_offset_sec = COALESCE($1::float8, start_offset_sec),
  end_offset_sec   = COALESCE($2::float8, end_offset_sec),
  geometry         = COALESCE($3::jsonb, geometry),
  style            = COALESCE($4::jsonb, style),
  label            = COALESCE($5, label)
WHERE id = $6
RETURNING id, video_id, author_id, start_offset_sec, end_offset_sec, type, geometry, style, label, created_at
`

type UpdateAnnotationParams struct {
	StartOffsetSec *float64
	EndOffsetSec   *float64
	Geometry       []byte
	Style          []byte
	Label          *string
	ID             pgtype.UUID
}

func (q *Queries) UpdateAnnotation(ctx context.Context, arg UpdateAnnotationParams) (Annotation, error) {
	row := q.db.QueryRow(ctx, updateAnnotation,
		arg.StartOffsetSec,
		arg.EndOffsetSec,
		arg.Geometry,
		arg.Style,
		arg.Label,
		arg.ID,
	)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.AuthorID,
		&i.StartOffsetSec,
		&i.EndOffsetSec,
		&i.Type,
		&i.Geometry,
		&i.Style,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}
