// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bulk_uploads.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearBulkUploadFingerprintsForTournament = `-- name: ClearBulkUploadFingerprintsForTournament :execrows
DELETE FROM bulk_upload_fingerprints WHERE tournament_id = $1
`

func (q *Queries) ClearBulkUploadFingerprintsForTournament(ctx context.Context, tournamentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearBulkUploadFingerprintsForTournament, tournamentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBulkUploadFingerprintsByHashes = `-- name: ListBulkUploadFingerprintsByHashes :many
SELECT f.id, f.tournament_id, f.head_hash, f.size_bytes, f.filename, f.media_kind, f.video_id, f.robot_image_id, f.created_at
FROM bulk_upload_fingerprints f
JOIN (
    SELECT UNNEST($1::bytea[]) AS head_hash,
           UNNEST($2::bigint[]) AS size_bytes
) AS q
  ON q.head_hash  = f.head_hash
 AND q.size_bytes = f.size_bytes
WHERE f.tournament_id = $3
`

type ListBulkUploadFingerprintsByHashesParams struct {
	HeadHashes    [][]byte
	SizeBytesList []int64
	TournamentID  pgtype.UUID
}

// Check API 用バッチ取得。 (head_hash, size_bytes) のペアを 2 つの配列で渡し、
// UNNEST で行に展開してジョインする。
func (q *Queries) ListBulkUploadFingerprintsByHashes(ctx context.Context, arg ListBulkUploadFingerprintsByHashesParams) ([]BulkUploadFingerprint, error) {
	rows, err := q.db.Query(ctx, listBulkUploadFingerprintsByHashes, arg.HeadHashes, arg.SizeBytesList, arg.TournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkUploadFingerprint
	for rows.Next() {
		var i BulkUploadFingerprint
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.HeadHash,
			&i.SizeBytes,
			&i.Filename,
			&i.MediaKind,
			&i.VideoID,
			&i.RobotImageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupBulkUploadFingerprint = `-- name: LookupBulkUploadFingerprint :one
SELECT id, tournament_id, head_hash, size_bytes, filename, media_kind, video_id, robot_image_id, created_at
FROM bulk_upload_fingerprints
WHERE tournament_id = $1
  AND head_hash     = $2
  AND size_bytes    = $3
`

type LookupBulkUploadFingerprintParams struct {
	TournamentID pgtype.UUID
	HeadHash     []byte
	SizeBytes    int64
}

// 1 件単位で (tournament, hash, size) を引く。 N+1 を避けるため Check API は
// これを並べて発行する代わりに ListBulkUploadFingerprintsByHashes を使う。
func (q *Queries) LookupBulkUploadFingerprint(ctx context.Context, arg LookupBulkUploadFingerprintParams) (BulkUploadFingerprint, error) {
	row := q.db.QueryRow(ctx, lookupBulkUploadFingerprint, arg.TournamentID, arg.HeadHash, arg.SizeBytes)
	var i BulkUploadFingerprint
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.HeadHash,
		&i.SizeBytes,
		&i.Filename,
		&i.MediaKind,
		&i.VideoID,
		&i.RobotImageID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertBulkUploadFingerprint = `-- name: UpsertBulkUploadFingerprint :one
INSERT INTO bulk_upload_fingerprints (
    tournament_id, head_hash, size_bytes, filename, media_kind,
    video_id, robot_image_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tournament_id, head_hash, size_bytes) DO UPDATE
SET filename        = EXCLUDED.filename,
    media_kind      = EXCLUDED.media_kind,
    video_id        = COALESCE(EXCLUDED.video_id,        bulk_upload_fingerprints.video_id),
    robot_image_id  = COALESCE(EXCLUDED.robot_image_id,  bulk_upload_fingerprints.robot_image_id)
RETURNING id, tournament_id, head_hash, size_bytes, filename, media_kind, video_id, robot_image_id, created_at
`

type UpsertBulkUploadFingerprintParams struct {
	TournamentID pgtype.UUID
	HeadHash     []byte
	SizeBytes    int64
	Filename     string
	MediaKind    string
	VideoID      pgtype.UUID
	RobotImageID pgtype.UUID
}

// 動画 / 画像 アップロード完了時に呼ぶ。 既存行があればメディア ID を
// 上書きする (race で同じ fingerprint が同時に飛んできても 1 行に収束)。
func (q *Queries) UpsertBulkUploadFingerprint(ctx context.Context, arg UpsertBulkUploadFingerprintParams) (BulkUploadFingerprint, error) {
	row := q.db.QueryRow(ctx, upsertBulkUploadFingerprint,
		arg.TournamentID,
		arg.HeadHash,
		arg.SizeBytes,
		arg.Filename,
		arg.MediaKind,
		arg.VideoID,
		arg.RobotImageID,
	)
	var i BulkUploadFingerprint
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.HeadHash,
		&i.SizeBytes,
		&i.Filename,
		&i.MediaKind,
		&i.VideoID,
		&i.RobotImageID,
		&i.CreatedAt,
	)
	return i, err
}
