// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlc

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (name, default_time_offset_sec)
VALUES ($1, $2)
RETURNING id, name, default_time_offset_sec, created_at
`

type CreateDeviceParams struct {
	Name                 string
	DefaultTimeOffsetSec int32
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.Name, arg.DefaultTimeOffsetSec)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultTimeOffsetSec,
		&i.CreatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, default_time_offset_sec, created_at FROM devices ORDER BY created_at ASC
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultTimeOffsetSec,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
