// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMarkersByTeamAndCategory = `-- name: CountMarkersByTeamAndCategory :many
SELECT m.category, COUNT(*) AS count
FROM markers m
JOIN runs r ON r.id = m.run_id
WHERE r.team_id = $1
GROUP BY m.category
`

type CountMarkersByTeamAndCategoryRow struct {
	Category MarkerCategory
	Count    int64
}

func (q *Queries) CountMarkersByTeamAndCategory(ctx context.Context, teamID pgtype.UUID) ([]CountMarkersByTeamAndCategoryRow, error) {
	rows, err := q.db.Query(ctx, countMarkersByTeamAndCategory, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountMarkersByTeamAndCategoryRow
	for rows.Next() {
		var i CountMarkersByTeamAndCategoryRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMarker = `-- name: CreateMarker :one
INSERT INTO markers (run_id, author_id, run_offset_sec, label, category)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, author_id, run_offset_sec, label, category, created_at
`

type CreateMarkerParams struct {
	RunID        pgtype.UUID
	AuthorID     pgtype.UUID
	RunOffsetSec int32
	Label        string
	Category     MarkerCategory
}

func (q *Queries) CreateMarker(ctx context.Context, arg CreateMarkerParams) (Marker, error) {
	row := q.db.QueryRow(ctx, createMarker,
		arg.RunID,
		arg.AuthorID,
		arg.RunOffsetSec,
		arg.Label,
		arg.Category,
	)
	var i Marker
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AuthorID,
		&i.RunOffsetSec,
		&i.Label,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMarker = `-- name: DeleteMarker :execrows
DELETE FROM markers WHERE id = $1
`

func (q *Queries) DeleteMarker(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMarker, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMarker = `-- name: GetMarker :one
SELECT id, run_id, author_id, run_offset_sec, label, category, created_at FROM markers WHERE id = $1
`

func (q *Queries) GetMarker(ctx context.Context, id pgtype.UUID) (Marker, error) {
	row := q.db.QueryRow(ctx, getMarker, id)
	var i Marker
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AuthorID,
		&i.RunOffsetSec,
		&i.Label,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const listMarkersByRun = `-- name: ListMarkersByRun :many
SELECT id, run_id, author_id, run_offset_sec, label, category, created_at
FROM markers
WHERE run_id = $2
  AND ($3::int IS NULL
       OR (run_offset_sec, id) > ($3::int, $4::uuid))
  AND (COALESCE(array_length($5::text[], 1), 0) = 0
       OR category::text = ANY($5::text[]))
ORDER BY run_offset_sec ASC, id ASC
LIMIT $1
`

type ListMarkersByRunParams struct {
	Limit           int32
	RunID           pgtype.UUID
	CursorRunOffset *int32
	CursorID        pgtype.UUID
	Categories      []string
}

func (q *Queries) ListMarkersByRun(ctx context.Context, arg ListMarkersByRunParams) ([]Marker, error) {
	rows, err := q.db.Query(ctx, listMarkersByRun,
		arg.Limit,
		arg.RunID,
		arg.CursorRunOffset,
		arg.CursorID,
		arg.Categories,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Marker
	for rows.Next() {
		var i Marker
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AuthorID,
			&i.RunOffsetSec,
			&i.Label,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarker = `-- name: UpdateMarker :one
UPDATE markers
SET
  run_offset_sec = COALESCE($1, run_offset_sec),
  label          = COALESCE($2, label),
  category       = COALESCE($3, category)
WHERE id = $4
RETURNING id, run_id, author_id, run_offset_sec, label, category, created_at
`

type UpdateMarkerParams struct {
	RunOffsetSec *int32
	Label        *string
	Category     NullMarkerCategory
	ID           pgtype.UUID
}

func (q *Queries) UpdateMarker(ctx context.Context, arg UpdateMarkerParams) (Marker, error) {
	row := q.db.QueryRow(ctx, updateMarker,
		arg.RunOffsetSec,
		arg.Label,
		arg.Category,
		arg.ID,
	)
	var i Marker
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AuthorID,
		&i.RunOffsetSec,
		&i.Label,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}
