// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (tournament_id, team_a_id, team_b_id, scheduled_at)
VALUES ($1, $2, $3, $4)
RETURNING id, tournament_id, team_a_id, team_b_id, scheduled_at, created_at
`

type CreateMatchParams struct {
	TournamentID pgtype.UUID
	TeamAID      pgtype.UUID
	TeamBID      pgtype.UUID
	ScheduledAt  pgtype.Timestamptz
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.TournamentID,
		arg.TeamAID,
		arg.TeamBID,
		arg.ScheduledAt,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.TeamAID,
		&i.TeamBID,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMatch = `-- name: DeleteMatch :execrows
DELETE FROM matches WHERE id = $1
`

func (q *Queries) DeleteMatch(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMatch, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMatch = `-- name: GetMatch :one
SELECT id, tournament_id, team_a_id, team_b_id, scheduled_at, created_at FROM matches WHERE id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.TeamAID,
		&i.TeamBID,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMatchesPage = `-- name: ListMatchesPage :many
SELECT id, tournament_id, team_a_id, team_b_id, scheduled_at, created_at
FROM matches
WHERE
  ($2::uuid IS NULL OR tournament_id = $2::uuid)
  AND ($3::timestamptz IS NULL
       OR (created_at, id) > ($3::timestamptz, $4::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $1
`

type ListMatchesPageParams struct {
	Limit           int32
	TournamentID    pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListMatchesPage(ctx context.Context, arg ListMatchesPageParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesPage,
		arg.Limit,
		arg.TournamentID,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.TeamAID,
			&i.TeamBID,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatch = `-- name: UpdateMatch :one
UPDATE matches
SET
  team_a_id    = COALESCE($1::uuid, team_a_id),
  team_b_id    = COALESCE($2::uuid, team_b_id),
  scheduled_at = CASE WHEN $3::bool THEN $4::timestamptz ELSE scheduled_at END
WHERE id = $5
RETURNING id, tournament_id, team_a_id, team_b_id, scheduled_at, created_at
`

type UpdateMatchParams struct {
	TeamAID        pgtype.UUID
	TeamBID        pgtype.UUID
	ScheduledAtSet bool
	ScheduledAt    pgtype.Timestamptz
	ID             pgtype.UUID
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatch,
		arg.TeamAID,
		arg.TeamBID,
		arg.ScheduledAtSet,
		arg.ScheduledAt,
		arg.ID,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.TeamAID,
		&i.TeamBID,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}
