// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnnotationType string

const (
	AnnotationTypePoint AnnotationType = "point"
	AnnotationTypeArrow AnnotationType = "arrow"
	AnnotationTypeRect  AnnotationType = "rect"
	AnnotationTypePath  AnnotationType = "path"
	AnnotationTypeText  AnnotationType = "text"
)

func (e *AnnotationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnnotationType(s)
	case string:
		*e = AnnotationType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnnotationType: %T", src)
	}
	return nil
}

type NullAnnotationType struct {
	AnnotationType AnnotationType
	Valid          bool // Valid is true if AnnotationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnnotationType) Scan(value interface{}) error {
	if value == nil {
		ns.AnnotationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnnotationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnnotationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnnotationType), nil
}

type HLSStatus string

const (
	HlsStatusPending  HLSStatus = "pending"
	HlsStatusPlanning HLSStatus = "planning"
	HlsStatusEncoding HLSStatus = "encoding"
	HlsStatusReady    HLSStatus = "ready"
	HlsStatusFailed   HLSStatus = "failed"
)

func (e *HLSStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HLSStatus(s)
	case string:
		*e = HLSStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HLSStatus: %T", src)
	}
	return nil
}

type NullHLSStatus struct {
	HLSStatus HLSStatus
	Valid     bool // Valid is true if HLSStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHLSStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HLSStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HLSStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHLSStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HLSStatus), nil
}

type MarkerCategory string

const (
	MarkerCategorySuccess MarkerCategory = "success"
	MarkerCategoryFailure MarkerCategory = "failure"
	MarkerCategoryNote    MarkerCategory = "note"
)

func (e *MarkerCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MarkerCategory(s)
	case string:
		*e = MarkerCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for MarkerCategory: %T", src)
	}
	return nil
}

type NullMarkerCategory struct {
	MarkerCategory MarkerCategory
	Valid          bool // Valid is true if MarkerCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMarkerCategory) Scan(value interface{}) error {
	if value == nil {
		ns.MarkerCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MarkerCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMarkerCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MarkerCategory), nil
}

type RenditionKind string

const (
	RenditionKindOriginal RenditionKind = "original"
	RenditionKind720p     RenditionKind = "720p"
	RenditionKind480p     RenditionKind = "480p"
)

func (e *RenditionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RenditionKind(s)
	case string:
		*e = RenditionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for RenditionKind: %T", src)
	}
	return nil
}

type NullRenditionKind struct {
	RenditionKind RenditionKind
	Valid         bool // Valid is true if RenditionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRenditionKind) Scan(value interface{}) error {
	if value == nil {
		ns.RenditionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RenditionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRenditionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RenditionKind), nil
}

type RenditionStatus string

const (
	RenditionStatusPending  RenditionStatus = "pending"
	RenditionStatusEncoding RenditionStatus = "encoding"
	RenditionStatusReady    RenditionStatus = "ready"
	RenditionStatusFailed   RenditionStatus = "failed"
)

func (e *RenditionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RenditionStatus(s)
	case string:
		*e = RenditionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RenditionStatus: %T", src)
	}
	return nil
}

type NullRenditionStatus struct {
	RenditionStatus RenditionStatus
	Valid           bool // Valid is true if RenditionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRenditionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RenditionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RenditionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRenditionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RenditionStatus), nil
}

type SessionModeHint string

const (
	SessionModeHintPractice SessionModeHint = "practice"
	SessionModeHintPreMatch SessionModeHint = "pre_match"
)

func (e *SessionModeHint) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionModeHint(s)
	case string:
		*e = SessionModeHint(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionModeHint: %T", src)
	}
	return nil
}

type NullSessionModeHint struct {
	SessionModeHint SessionModeHint
	Valid           bool // Valid is true if SessionModeHint is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionModeHint) Scan(value interface{}) error {
	if value == nil {
		ns.SessionModeHint, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionModeHint.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionModeHint) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionModeHint), nil
}

type Annotation struct {
	ID             pgtype.UUID
	VideoID        pgtype.UUID
	AuthorID       pgtype.UUID
	StartOffsetSec float64
	EndOffsetSec   float64
	Type           AnnotationType
	Geometry       []byte
	Style          []byte
	Label          string
	CreatedAt      pgtype.Timestamptz
}

type BulkUploadFingerprint struct {
	ID           pgtype.UUID
	TournamentID pgtype.UUID
	HeadHash     []byte
	SizeBytes    int64
	Filename     string
	MediaKind    string
	VideoID      pgtype.UUID
	RobotImageID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type Device struct {
	ID                   pgtype.UUID
	Name                 string
	DefaultTimeOffsetSec int32
	CreatedAt            pgtype.Timestamptz
}

type Marker struct {
	ID           pgtype.UUID
	RunID        pgtype.UUID
	AuthorID     pgtype.UUID
	RunOffsetSec int32
	Label        string
	Category     MarkerCategory
	CreatedAt    pgtype.Timestamptz
}

type Match struct {
	ID           pgtype.UUID
	TournamentID pgtype.UUID
	TeamAID      pgtype.UUID
	TeamBID      pgtype.UUID
	ScheduledAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Robot struct {
	ID             pgtype.UUID
	TeamID         pgtype.UUID
	Name           string
	Version        string
	CreatedAt      pgtype.Timestamptz
	PrimaryImageID pgtype.UUID
}

type RobotImage struct {
	ID                 pgtype.UUID
	RobotID            pgtype.UUID
	StorageKey         string
	ContentType        string
	DisplayKey         *string
	DisplayContentType *string
	ThumbnailKey       string
	SizeBytes          int64
	Width              *int32
	Height             *int32
	CapturedAt         pgtype.Timestamptz
	ExifOrientation    *int16
	Caption            string
	UploaderID         pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	SortAt             pgtype.Timestamptz
}

type Run struct {
	ID           pgtype.UUID
	SessionID    pgtype.UUID
	TeamID       pgtype.UUID
	RobotID      pgtype.UUID
	ScenarioID   pgtype.UUID
	MatchID      pgtype.UUID
	StartedAt    pgtype.Timestamptz
	Score        *float64
	Memo         string
	CreatedAt    pgtype.Timestamptz
	DurationSec  int32
	TournamentID pgtype.UUID
}

type RunTag struct {
	RunID pgtype.UUID
	TagID pgtype.UUID
}

type RunVideo struct {
	ID               pgtype.UUID
	RunID            pgtype.UUID
	VideoID          pgtype.UUID
	VideoOffsetStart int32
	VideoOffsetEnd   int32
	AngleLabel       string
	CreatedAt        pgtype.Timestamptz
	RunOffsetSec     int32
}

type Scenario struct {
	ID          pgtype.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type ScoutingNote struct {
	ID           pgtype.UUID
	YdocState    []byte
	PlainText    string
	UpdatedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	TournamentID pgtype.UUID
	TeamID       pgtype.UUID
}

type Session struct {
	ID           pgtype.UUID
	Name         string
	StartedAt    pgtype.Timestamptz
	EndedAt      pgtype.Timestamptz
	Location     *string
	ModeHint     SessionModeHint
	TournamentID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type Tag struct {
	ID        pgtype.UUID
	Name      string
	Color     *string
	CreatedAt pgtype.Timestamptz
}

type Team struct {
	ID        pgtype.UUID
	Name      string
	IsOwn     bool
	CreatedAt pgtype.Timestamptz
}

type Tournament struct {
	ID        pgtype.UUID
	Name      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type TournamentRobot struct {
	TournamentID pgtype.UUID
	RobotID      pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type TournamentTeam struct {
	TournamentID pgtype.UUID
	TeamID       pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Color     *string
	CreatedAt pgtype.Timestamptz
	OidcSub   *string
	Email     *string
}

type Video struct {
	ID               pgtype.UUID
	SessionID        pgtype.UUID
	DeviceID         pgtype.UUID
	UploaderID       pgtype.UUID
	StorageKey       string
	RecordedAt       pgtype.Timestamptz
	DurationSec      *int32
	TimeOffsetSec    int32
	CreatedAt        pgtype.Timestamptz
	ThumbnailKey     *string
	DisplayName      string
	HlsMasterKey     *string
	HLSStatus        HLSStatus
	SourceVideoCodec *string
	SourceAudioCodec *string
	SourceWidth      *int32
	SourceHeight     *int32
	PassthroughOk    bool
	TournamentID     pgtype.UUID
}

type VideoRendition struct {
	ID           pgtype.UUID
	VideoID      pgtype.UUID
	Kind         RenditionKind
	Status       RenditionStatus
	Passthrough  bool
	Width        int32
	Height       int32
	BandwidthBps *int32
	PlaylistKey  string
	SegmentsDone int32
	Error        *string
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type VideoTag struct {
	VideoID pgtype.UUID
	TagID   pgtype.UUID
}
