// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnnotationType string

const (
	AnnotationTypePoint AnnotationType = "point"
	AnnotationTypeArrow AnnotationType = "arrow"
	AnnotationTypeRect  AnnotationType = "rect"
	AnnotationTypePath  AnnotationType = "path"
	AnnotationTypeText  AnnotationType = "text"
)

func (e *AnnotationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnnotationType(s)
	case string:
		*e = AnnotationType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnnotationType: %T", src)
	}
	return nil
}

type NullAnnotationType struct {
	AnnotationType AnnotationType
	Valid          bool // Valid is true if AnnotationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnnotationType) Scan(value interface{}) error {
	if value == nil {
		ns.AnnotationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnnotationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnnotationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnnotationType), nil
}

type MarkerCategory string

const (
	MarkerCategorySuccess MarkerCategory = "success"
	MarkerCategoryFailure MarkerCategory = "failure"
	MarkerCategoryNote    MarkerCategory = "note"
)

func (e *MarkerCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MarkerCategory(s)
	case string:
		*e = MarkerCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for MarkerCategory: %T", src)
	}
	return nil
}

type NullMarkerCategory struct {
	MarkerCategory MarkerCategory
	Valid          bool // Valid is true if MarkerCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMarkerCategory) Scan(value interface{}) error {
	if value == nil {
		ns.MarkerCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MarkerCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMarkerCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MarkerCategory), nil
}

type SessionModeHint string

const (
	SessionModeHintPractice SessionModeHint = "practice"
	SessionModeHintPreMatch SessionModeHint = "pre_match"
)

func (e *SessionModeHint) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionModeHint(s)
	case string:
		*e = SessionModeHint(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionModeHint: %T", src)
	}
	return nil
}

type NullSessionModeHint struct {
	SessionModeHint SessionModeHint
	Valid           bool // Valid is true if SessionModeHint is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionModeHint) Scan(value interface{}) error {
	if value == nil {
		ns.SessionModeHint, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionModeHint.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionModeHint) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionModeHint), nil
}

type Annotation struct {
	ID             pgtype.UUID
	VideoID        pgtype.UUID
	AuthorID       pgtype.UUID
	StartOffsetSec float64
	EndOffsetSec   float64
	Type           AnnotationType
	Geometry       []byte
	Style          []byte
	Label          string
	CreatedAt      pgtype.Timestamptz
}

type Device struct {
	ID                   pgtype.UUID
	Name                 string
	DefaultTimeOffsetSec int32
	CreatedAt            pgtype.Timestamptz
}

type Marker struct {
	ID           pgtype.UUID
	RunID        pgtype.UUID
	AuthorID     pgtype.UUID
	RunOffsetSec int32
	Label        string
	Category     MarkerCategory
	CreatedAt    pgtype.Timestamptz
}

type Match struct {
	ID           pgtype.UUID
	TournamentID pgtype.UUID
	TeamAID      pgtype.UUID
	TeamBID      pgtype.UUID
	ScheduledAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Robot struct {
	ID        pgtype.UUID
	TeamID    pgtype.UUID
	Name      string
	Version   string
	CreatedAt pgtype.Timestamptz
}

type Run struct {
	ID         pgtype.UUID
	SessionID  pgtype.UUID
	TeamID     pgtype.UUID
	RobotID    pgtype.UUID
	ScenarioID pgtype.UUID
	MatchID    pgtype.UUID
	StartedAt  pgtype.Timestamptz
	EndedAt    pgtype.Timestamptz
	Score      *float64
	Memo       string
	CreatedAt  pgtype.Timestamptz
}

type RunTag struct {
	RunID pgtype.UUID
	TagID pgtype.UUID
}

type RunVideo struct {
	ID               pgtype.UUID
	RunID            pgtype.UUID
	VideoID          pgtype.UUID
	VideoOffsetStart int32
	VideoOffsetEnd   int32
	AngleLabel       string
	CreatedAt        pgtype.Timestamptz
}

type Scenario struct {
	ID          pgtype.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type ScoutingNote struct {
	ID           pgtype.UUID
	MatchID      pgtype.UUID
	TargetTeamID pgtype.UUID
	YdocState    []byte
	PlainText    string
	UpdatedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Session struct {
	ID           pgtype.UUID
	Name         string
	StartedAt    pgtype.Timestamptz
	EndedAt      pgtype.Timestamptz
	Location     *string
	ModeHint     SessionModeHint
	TournamentID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type Tag struct {
	ID        pgtype.UUID
	Name      string
	Color     *string
	CreatedAt pgtype.Timestamptz
}

type Team struct {
	ID        pgtype.UUID
	Name      string
	IsOwn     bool
	CreatedAt pgtype.Timestamptz
}

type Tournament struct {
	ID        pgtype.UUID
	Name      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Color     *string
	CreatedAt pgtype.Timestamptz
}

type Video struct {
	ID            pgtype.UUID
	SessionID     pgtype.UUID
	DeviceID      pgtype.UUID
	UploaderID    pgtype.UUID
	StorageKey    string
	RecordedAt    pgtype.Timestamptz
	DurationSec   *int32
	TimeOffsetSec int32
	CreatedAt     pgtype.Timestamptz
	ThumbnailKey  *string
}

type VideoTag struct {
	VideoID pgtype.UUID
	TagID   pgtype.UUID
}
