// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateRobot(ctx context.Context, arg CreateRobotParams) (Robot, error)
	CreateScenario(ctx context.Context, arg CreateScenarioParams) (Scenario, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDevice(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteRobot(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteScenario(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteTag(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteTeam(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error)
	GetDevice(ctx context.Context, id pgtype.UUID) (Device, error)
	GetOwnTeam(ctx context.Context) (Team, error)
	GetRobot(ctx context.Context, id pgtype.UUID) (Robot, error)
	GetScenario(ctx context.Context, id pgtype.UUID) (Scenario, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetTag(ctx context.Context, id pgtype.UUID) (Tag, error)
	GetTeam(ctx context.Context, id pgtype.UUID) (Team, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	ListDevices(ctx context.Context) ([]Device, error)
	ListDevicesPage(ctx context.Context, arg ListDevicesPageParams) ([]Device, error)
	ListRobotsByTeam(ctx context.Context, teamID pgtype.UUID) ([]Robot, error)
	ListRobotsPage(ctx context.Context, arg ListRobotsPageParams) ([]Robot, error)
	ListScenarios(ctx context.Context) ([]Scenario, error)
	ListScenariosPage(ctx context.Context, arg ListScenariosPageParams) ([]Scenario, error)
	ListSessionsPage(ctx context.Context, arg ListSessionsPageParams) ([]Session, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsPage(ctx context.Context, arg ListTagsPageParams) ([]Tag, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListTeamsPage(ctx context.Context, arg ListTeamsPageParams) ([]Team, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]User, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
	UpdateRobot(ctx context.Context, arg UpdateRobotParams) (Robot, error)
	UpdateScenario(ctx context.Context, arg UpdateScenarioParams) (Scenario, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
