// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRunTag(ctx context.Context, arg AddRunTagParams) error
	AddRunVideo(ctx context.Context, arg AddRunVideoParams) (RunVideo, error)
	AddTournamentRobot(ctx context.Context, arg AddTournamentRobotParams) error
	AddTournamentTeam(ctx context.Context, arg AddTournamentTeamParams) error
	// 画像削除時に primary が同じ id を指していたら NULL に戻す。FK の
	// ON DELETE SET NULL でも同じ結果になるが、明示的に呼べると分かりやすい。
	ClearRobotPrimaryImageIfMatches(ctx context.Context, arg ClearRobotPrimaryImageIfMatchesParams) error
	ClearRunTags(ctx context.Context, runID pgtype.UUID) error
	ClearTournamentRobots(ctx context.Context, tournamentID pgtype.UUID) error
	ClearTournamentTeams(ctx context.Context, tournamentID pgtype.UUID) error
	CountMarkersByTeamAndCategory(ctx context.Context, teamID pgtype.UUID) ([]CountMarkersByTeamAndCategoryRow, error)
	CountRenditionsByStatus(ctx context.Context, videoID pgtype.UUID) (CountRenditionsByStatusRow, error)
	CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateMarker(ctx context.Context, arg CreateMarkerParams) (Marker, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateRobot(ctx context.Context, arg CreateRobotParams) (Robot, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateScenario(ctx context.Context, arg CreateScenarioParams) (Scenario, error)
	// ScoutingNote rows: ydoc_state / plain_text は Hocuspocus が更新するため
	// Go API は CRUD と GET だけを公開する。
	CreateScoutingNote(ctx context.Context, arg CreateScoutingNoteParams) (ScoutingNote, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserFromOIDC(ctx context.Context, arg CreateUserFromOIDCParams) (User, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteAnnotation(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteDevice(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteMarker(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteMatch(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteRobot(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteRobotImage(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteRun(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteRunVideo(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteRunVideoByRunAndVideo(ctx context.Context, arg DeleteRunVideoByRunAndVideoParams) (int64, error)
	DeleteScenario(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteScoutingNote(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteTag(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteTeam(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteTournament(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteVideo(ctx context.Context, id pgtype.UUID) (int64, error)
	GetAnnotation(ctx context.Context, id pgtype.UUID) (Annotation, error)
	GetDevice(ctx context.Context, id pgtype.UUID) (Device, error)
	GetMarker(ctx context.Context, id pgtype.UUID) (Marker, error)
	GetMatch(ctx context.Context, id pgtype.UUID) (Match, error)
	GetOwnTeam(ctx context.Context) (Team, error)
	GetRendition(ctx context.Context, id pgtype.UUID) (VideoRendition, error)
	GetRobot(ctx context.Context, id pgtype.UUID) (Robot, error)
	GetRobotImage(ctx context.Context, id pgtype.UUID) (RobotImage, error)
	GetRun(ctx context.Context, id pgtype.UUID) (Run, error)
	GetRunVideo(ctx context.Context, id pgtype.UUID) (RunVideo, error)
	GetScenario(ctx context.Context, id pgtype.UUID) (Scenario, error)
	GetScoutingNote(ctx context.Context, id pgtype.UUID) (ScoutingNote, error)
	GetScoutingNoteByMatchAndTeam(ctx context.Context, arg GetScoutingNoteByMatchAndTeamParams) (ScoutingNote, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetTag(ctx context.Context, id pgtype.UUID) (Tag, error)
	GetTeam(ctx context.Context, id pgtype.UUID) (Team, error)
	GetTournament(ctx context.Context, id pgtype.UUID) (Tournament, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, dollar_1 string) (User, error)
	GetUserByOIDCSub(ctx context.Context, oidcSub *string) (User, error)
	GetVideo(ctx context.Context, id pgtype.UUID) (Video, error)
	GetVideoByStorageKey(ctx context.Context, storageKey string) (Video, error)
	IncrementRenditionSegments(ctx context.Context, id pgtype.UUID) (int64, error)
	InsertRendition(ctx context.Context, arg InsertRenditionParams) (VideoRendition, error)
	InsertRobotImage(ctx context.Context, arg InsertRobotImageParams) (RobotImage, error)
	LinkUserOIDC(ctx context.Context, arg LinkUserOIDCParams) (User, error)
	ListAnnotationsByVideo(ctx context.Context, videoID pgtype.UUID) ([]Annotation, error)
	ListDevices(ctx context.Context) ([]Device, error)
	ListDevicesPage(ctx context.Context, arg ListDevicesPageParams) ([]Device, error)
	// Videos that are mid-encode (hls_status in planning/encoding) or have failed
	// recently. Returned newest first so the dashboard shows current activity at
	// the top.
	ListEncodingVideos(ctx context.Context, limit int32) ([]Video, error)
	ListMarkersByRun(ctx context.Context, arg ListMarkersByRunParams) ([]Marker, error)
	ListMatchesPage(ctx context.Context, arg ListMatchesPageParams) ([]Match, error)
	// Videos uploaded against the Run's session that are not yet attached to it.
	// Used to populate the "Run に追加すべき動画" recommendation list.
	ListRecommendedVideosForRun(ctx context.Context, id pgtype.UUID) ([]Video, error)
	ListRenditionsByVideo(ctx context.Context, videoID pgtype.UUID) ([]VideoRendition, error)
	ListRenditionsByVideos(ctx context.Context, videoIds []pgtype.UUID) ([]VideoRendition, error)
	// 任意で captured_at 範囲を絞れる。range が NULL の側は無制限。
	// sort 方向は caller が `order` で 'asc' / 'desc' を渡す (空なら asc)。
	ListRobotImagesByRobot(ctx context.Context, arg ListRobotImagesByRobotParams) ([]RobotImage, error)
	ListRobotsByTeam(ctx context.Context, teamID pgtype.UUID) ([]Robot, error)
	ListRobotsByTournament(ctx context.Context, tournamentID pgtype.UUID) ([]Robot, error)
	ListRobotsPage(ctx context.Context, arg ListRobotsPageParams) ([]Robot, error)
	ListRunTagsByRun(ctx context.Context, runID pgtype.UUID) ([]pgtype.UUID, error)
	ListRunVideosByRun(ctx context.Context, runID pgtype.UUID) ([]RunVideo, error)
	ListRunsPage(ctx context.Context, arg ListRunsPageParams) ([]Run, error)
	ListScenarios(ctx context.Context) ([]Scenario, error)
	ListScenariosPage(ctx context.Context, arg ListScenariosPageParams) ([]Scenario, error)
	ListScoutingNotesByMatch(ctx context.Context, matchID pgtype.UUID) ([]ScoutingNote, error)
	// Sessions that either:
	//   (a) contain the video's time range (treating ended_at IS NULL as an
	//       ongoing / open session that extends to +infinity), or
	//   (b) are adjacent within the caller's gap window. The caller passes
	//       window_start = videoStart - gap_threshold and window_end =
	//       videoEnd + gap_threshold.
	// Open sessions (ended_at IS NULL) match regardless of how old their
	// started_at is, so a forgotten "in progress" session still appears for
	// today's upload — that's exactly the post-hoc linking UX we want.
	ListSessionCandidatesForVideo(ctx context.Context, arg ListSessionCandidatesForVideoParams) ([]Session, error)
	ListSessionsPage(ctx context.Context, arg ListSessionsPageParams) ([]Session, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsPage(ctx context.Context, arg ListTagsPageParams) ([]Tag, error)
	ListTeams(ctx context.Context) ([]Team, error)
	// ---------- Tournament <-> Team / Robot links (P0) ----------
	ListTeamsByTournament(ctx context.Context, tournamentID pgtype.UUID) ([]Team, error)
	ListTeamsPage(ctx context.Context, arg ListTeamsPageParams) ([]Team, error)
	// 整合性チェック用: PUT /tournaments/{id}/robots で渡された各 robot の team_id が
	// 大会の参加チームに含まれているかを検証するために、対象 robot_ids の team_id を一括取得する。
	ListTournamentRobotsTeamIDs(ctx context.Context, robotIds []pgtype.UUID) ([]ListTournamentRobotsTeamIDsRow, error)
	ListTournamentsPage(ctx context.Context, arg ListTournamentsPageParams) ([]Tournament, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]User, error)
	ListVideosPage(ctx context.Context, arg ListVideosPageParams) ([]Video, error)
	MarkRenditionEncoding(ctx context.Context, id pgtype.UUID) (int64, error)
	MarkRenditionFailed(ctx context.Context, arg MarkRenditionFailedParams) (int64, error)
	MarkRenditionReady(ctx context.Context, arg MarkRenditionReadyParams) (int64, error)
	RemoveTournamentRobot(ctx context.Context, arg RemoveTournamentRobotParams) (int64, error)
	RemoveTournamentTeam(ctx context.Context, arg RemoveTournamentTeamParams) (int64, error)
	SearchRuns(ctx context.Context, arg SearchRunsParams) ([]Run, error)
	SetRobotPrimaryImage(ctx context.Context, arg SetRobotPrimaryImageParams) error
	UpdateAnnotation(ctx context.Context, arg UpdateAnnotationParams) (Annotation, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
	UpdateMarker(ctx context.Context, arg UpdateMarkerParams) (Marker, error)
	UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error)
	UpdateRobot(ctx context.Context, arg UpdateRobotParams) (Robot, error)
	UpdateRobotImage(ctx context.Context, arg UpdateRobotImageParams) (RobotImage, error)
	UpdateRun(ctx context.Context, arg UpdateRunParams) (Run, error)
	UpdateRunVideo(ctx context.Context, arg UpdateRunVideoParams) (RunVideo, error)
	UpdateScenario(ctx context.Context, arg UpdateScenarioParams) (Scenario, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateTournament(ctx context.Context, arg UpdateTournamentParams) (Tournament, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error)
	UpdateVideoHLSReady(ctx context.Context, arg UpdateVideoHLSReadyParams) (int64, error)
	UpdateVideoHLSStatus(ctx context.Context, arg UpdateVideoHLSStatusParams) (int64, error)
	UpdateVideoProbe(ctx context.Context, arg UpdateVideoProbeParams) (Video, error)
	UpdateVideoSource(ctx context.Context, arg UpdateVideoSourceParams) (int64, error)
	UpdateVideoThumbnail(ctx context.Context, arg UpdateVideoThumbnailParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
