// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateRobot(ctx context.Context, arg CreateRobotParams) (Robot, error)
	CreateScenario(ctx context.Context, arg CreateScenarioParams) (Scenario, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetOwnTeam(ctx context.Context) (Team, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	ListDevices(ctx context.Context) ([]Device, error)
	ListRobotsByTeam(ctx context.Context, teamID pgtype.UUID) ([]Robot, error)
	ListScenarios(ctx context.Context) ([]Scenario, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
