// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: renditions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRenditionsByStatus = `-- name: CountRenditionsByStatus :one
SELECT
  COUNT(*)                                       AS total,
  COUNT(*) FILTER (WHERE status = 'ready')       AS ready_count,
  COUNT(*) FILTER (WHERE status = 'failed')      AS failed_count
FROM video_renditions
WHERE video_id = $1
`

type CountRenditionsByStatusRow struct {
	Total       int64
	ReadyCount  int64
	FailedCount int64
}

func (q *Queries) CountRenditionsByStatus(ctx context.Context, videoID pgtype.UUID) (CountRenditionsByStatusRow, error) {
	row := q.db.QueryRow(ctx, countRenditionsByStatus, videoID)
	var i CountRenditionsByStatusRow
	err := row.Scan(&i.Total, &i.ReadyCount, &i.FailedCount)
	return i, err
}

const getRendition = `-- name: GetRendition :one
SELECT id, video_id, kind, status, passthrough, width, height, bandwidth_bps, playlist_key, segments_done, error, started_at, completed_at, updated_at FROM video_renditions WHERE id = $1
`

func (q *Queries) GetRendition(ctx context.Context, id pgtype.UUID) (VideoRendition, error) {
	row := q.db.QueryRow(ctx, getRendition, id)
	var i VideoRendition
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Kind,
		&i.Status,
		&i.Passthrough,
		&i.Width,
		&i.Height,
		&i.BandwidthBps,
		&i.PlaylistKey,
		&i.SegmentsDone,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementRenditionSegments = `-- name: IncrementRenditionSegments :execrows
UPDATE video_renditions
SET segments_done = segments_done + 1,
    updated_at    = now()
WHERE id = $1
`

func (q *Queries) IncrementRenditionSegments(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementRenditionSegments, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRendition = `-- name: InsertRendition :one
INSERT INTO video_renditions (
  video_id, kind, passthrough, width, height, bandwidth_bps, playlist_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (video_id, kind) DO UPDATE
SET passthrough   = EXCLUDED.passthrough,
    width         = EXCLUDED.width,
    height        = EXCLUDED.height,
    bandwidth_bps = EXCLUDED.bandwidth_bps,
    playlist_key  = EXCLUDED.playlist_key,
    updated_at    = now()
RETURNING id, video_id, kind, status, passthrough, width, height, bandwidth_bps, playlist_key, segments_done, error, started_at, completed_at, updated_at
`

type InsertRenditionParams struct {
	VideoID      pgtype.UUID
	Kind         RenditionKind
	Passthrough  bool
	Width        int32
	Height       int32
	BandwidthBps *int32
	PlaylistKey  string
}

func (q *Queries) InsertRendition(ctx context.Context, arg InsertRenditionParams) (VideoRendition, error) {
	row := q.db.QueryRow(ctx, insertRendition,
		arg.VideoID,
		arg.Kind,
		arg.Passthrough,
		arg.Width,
		arg.Height,
		arg.BandwidthBps,
		arg.PlaylistKey,
	)
	var i VideoRendition
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Kind,
		&i.Status,
		&i.Passthrough,
		&i.Width,
		&i.Height,
		&i.BandwidthBps,
		&i.PlaylistKey,
		&i.SegmentsDone,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEncodingVideos = `-- name: ListEncodingVideos :many
SELECT id, session_id, device_id, uploader_id, storage_key, recorded_at, duration_sec, time_offset_sec, created_at, thumbnail_key, display_name, hls_master_key, hls_status, source_video_codec, source_audio_codec, source_width, source_height, passthrough_ok FROM videos
WHERE hls_status IN ('planning', 'encoding', 'failed')
ORDER BY created_at DESC
LIMIT $1
`

// Videos that are mid-encode (hls_status in planning/encoding) or have failed
// recently. Returned newest first so the dashboard shows current activity at
// the top.
func (q *Queries) ListEncodingVideos(ctx context.Context, limit int32) ([]Video, error) {
	rows, err := q.db.Query(ctx, listEncodingVideos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DeviceID,
			&i.UploaderID,
			&i.StorageKey,
			&i.RecordedAt,
			&i.DurationSec,
			&i.TimeOffsetSec,
			&i.CreatedAt,
			&i.ThumbnailKey,
			&i.DisplayName,
			&i.HlsMasterKey,
			&i.HLSStatus,
			&i.SourceVideoCodec,
			&i.SourceAudioCodec,
			&i.SourceWidth,
			&i.SourceHeight,
			&i.PassthroughOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenditionsByVideo = `-- name: ListRenditionsByVideo :many
SELECT id, video_id, kind, status, passthrough, width, height, bandwidth_bps, playlist_key, segments_done, error, started_at, completed_at, updated_at FROM video_renditions
WHERE video_id = $1
ORDER BY kind ASC
`

func (q *Queries) ListRenditionsByVideo(ctx context.Context, videoID pgtype.UUID) ([]VideoRendition, error) {
	rows, err := q.db.Query(ctx, listRenditionsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoRendition
	for rows.Next() {
		var i VideoRendition
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Kind,
			&i.Status,
			&i.Passthrough,
			&i.Width,
			&i.Height,
			&i.BandwidthBps,
			&i.PlaylistKey,
			&i.SegmentsDone,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenditionsByVideos = `-- name: ListRenditionsByVideos :many
SELECT id, video_id, kind, status, passthrough, width, height, bandwidth_bps, playlist_key, segments_done, error, started_at, completed_at, updated_at FROM video_renditions
WHERE video_id = ANY($1::uuid[])
ORDER BY video_id ASC, kind ASC
`

func (q *Queries) ListRenditionsByVideos(ctx context.Context, videoIds []pgtype.UUID) ([]VideoRendition, error) {
	rows, err := q.db.Query(ctx, listRenditionsByVideos, videoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoRendition
	for rows.Next() {
		var i VideoRendition
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Kind,
			&i.Status,
			&i.Passthrough,
			&i.Width,
			&i.Height,
			&i.BandwidthBps,
			&i.PlaylistKey,
			&i.SegmentsDone,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRenditionEncoding = `-- name: MarkRenditionEncoding :execrows
UPDATE video_renditions
SET status       = 'encoding',
    started_at   = COALESCE(started_at, now()),
    segments_done = 0,
    error        = NULL,
    updated_at   = now()
WHERE id = $1
`

func (q *Queries) MarkRenditionEncoding(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markRenditionEncoding, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRenditionFailed = `-- name: MarkRenditionFailed :execrows
UPDATE video_renditions
SET status     = 'failed',
    error      = $1::text,
    updated_at = now()
WHERE id = $2::uuid
`

type MarkRenditionFailedParams struct {
	Error string
	ID    pgtype.UUID
}

func (q *Queries) MarkRenditionFailed(ctx context.Context, arg MarkRenditionFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRenditionFailed, arg.Error, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRenditionReady = `-- name: MarkRenditionReady :execrows
UPDATE video_renditions
SET status        = 'ready',
    completed_at  = now(),
    bandwidth_bps = COALESCE($1::int, bandwidth_bps),
    updated_at    = now()
WHERE id = $2::uuid
`

type MarkRenditionReadyParams struct {
	BandwidthBps *int32
	ID           pgtype.UUID
}

func (q *Queries) MarkRenditionReady(ctx context.Context, arg MarkRenditionReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRenditionReady, arg.BandwidthBps, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
