// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: robots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRobot = `-- name: CreateRobot :one
INSERT INTO robots (team_id, name, version)
VALUES ($1, $2, $3)
RETURNING id, team_id, name, version, created_at
`

type CreateRobotParams struct {
	TeamID  pgtype.UUID
	Name    string
	Version string
}

func (q *Queries) CreateRobot(ctx context.Context, arg CreateRobotParams) (Robot, error) {
	row := q.db.QueryRow(ctx, createRobot, arg.TeamID, arg.Name, arg.Version)
	var i Robot
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const listRobotsByTeam = `-- name: ListRobotsByTeam :many
SELECT id, team_id, name, version, created_at FROM robots WHERE team_id = $1 ORDER BY name, version
`

func (q *Queries) ListRobotsByTeam(ctx context.Context, teamID pgtype.UUID) ([]Robot, error) {
	rows, err := q.db.Query(ctx, listRobotsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Robot
	for rows.Next() {
		var i Robot
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
