// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: robot_images.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRobotPrimaryImageIfMatches = `-- name: ClearRobotPrimaryImageIfMatches :exec
UPDATE robots SET primary_image_id = NULL
WHERE id = $1 AND primary_image_id = $2
`

type ClearRobotPrimaryImageIfMatchesParams struct {
	RobotID pgtype.UUID
	ImageID pgtype.UUID
}

// 画像削除時に primary が同じ id を指していたら NULL に戻す。FK の
// ON DELETE SET NULL でも同じ結果になるが、明示的に呼べると分かりやすい。
func (q *Queries) ClearRobotPrimaryImageIfMatches(ctx context.Context, arg ClearRobotPrimaryImageIfMatchesParams) error {
	_, err := q.db.Exec(ctx, clearRobotPrimaryImageIfMatches, arg.RobotID, arg.ImageID)
	return err
}

const deleteRobotImage = `-- name: DeleteRobotImage :execrows
DELETE FROM robot_images WHERE id = $1
`

func (q *Queries) DeleteRobotImage(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRobotImage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRobotImage = `-- name: GetRobotImage :one
SELECT id, robot_id, storage_key, content_type, display_key, display_content_type, thumbnail_key, size_bytes, width, height, captured_at, exif_orientation, caption, uploader_id, created_at, sort_at FROM robot_images WHERE id = $1
`

func (q *Queries) GetRobotImage(ctx context.Context, id pgtype.UUID) (RobotImage, error) {
	row := q.db.QueryRow(ctx, getRobotImage, id)
	var i RobotImage
	err := row.Scan(
		&i.ID,
		&i.RobotID,
		&i.StorageKey,
		&i.ContentType,
		&i.DisplayKey,
		&i.DisplayContentType,
		&i.ThumbnailKey,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.CapturedAt,
		&i.ExifOrientation,
		&i.Caption,
		&i.UploaderID,
		&i.CreatedAt,
		&i.SortAt,
	)
	return i, err
}

const insertRobotImage = `-- name: InsertRobotImage :one
INSERT INTO robot_images (
    id, robot_id, storage_key, content_type,
    display_key, display_content_type,
    thumbnail_key, size_bytes, width, height,
    captured_at, exif_orientation,
    caption, uploader_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9, $10,
    $11, $12,
    $13, $14
)
RETURNING id, robot_id, storage_key, content_type, display_key, display_content_type, thumbnail_key, size_bytes, width, height, captured_at, exif_orientation, caption, uploader_id, created_at, sort_at
`

type InsertRobotImageParams struct {
	ID                 pgtype.UUID
	RobotID            pgtype.UUID
	StorageKey         string
	ContentType        string
	DisplayKey         *string
	DisplayContentType *string
	ThumbnailKey       string
	SizeBytes          int64
	Width              *int32
	Height             *int32
	CapturedAt         pgtype.Timestamptz
	ExifOrientation    *int16
	Caption            string
	UploaderID         pgtype.UUID
}

func (q *Queries) InsertRobotImage(ctx context.Context, arg InsertRobotImageParams) (RobotImage, error) {
	row := q.db.QueryRow(ctx, insertRobotImage,
		arg.ID,
		arg.RobotID,
		arg.StorageKey,
		arg.ContentType,
		arg.DisplayKey,
		arg.DisplayContentType,
		arg.ThumbnailKey,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.CapturedAt,
		arg.ExifOrientation,
		arg.Caption,
		arg.UploaderID,
	)
	var i RobotImage
	err := row.Scan(
		&i.ID,
		&i.RobotID,
		&i.StorageKey,
		&i.ContentType,
		&i.DisplayKey,
		&i.DisplayContentType,
		&i.ThumbnailKey,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.CapturedAt,
		&i.ExifOrientation,
		&i.Caption,
		&i.UploaderID,
		&i.CreatedAt,
		&i.SortAt,
	)
	return i, err
}

const listRobotImagesByRobot = `-- name: ListRobotImagesByRobot :many
SELECT id, robot_id, storage_key, content_type, display_key, display_content_type, thumbnail_key, size_bytes, width, height, captured_at, exif_orientation, caption, uploader_id, created_at, sort_at
FROM robot_images
WHERE robot_id = $1
  AND ($2::timestamptz IS NULL OR sort_at >= $2::timestamptz)
  AND ($3::timestamptz   IS NULL OR sort_at <= $3::timestamptz)
ORDER BY
  CASE WHEN $4::text = 'desc' THEN sort_at END DESC,
  CASE WHEN $4::text <> 'desc' THEN sort_at END ASC,
  id ASC
`

type ListRobotImagesByRobotParams struct {
	RobotID pgtype.UUID
	FromAt  pgtype.Timestamptz
	ToAt    pgtype.Timestamptz
	Order   string
}

// 任意で captured_at 範囲を絞れる。range が NULL の側は無制限。
// sort 方向は caller が `order` で 'asc' / 'desc' を渡す (空なら asc)。
func (q *Queries) ListRobotImagesByRobot(ctx context.Context, arg ListRobotImagesByRobotParams) ([]RobotImage, error) {
	rows, err := q.db.Query(ctx, listRobotImagesByRobot,
		arg.RobotID,
		arg.FromAt,
		arg.ToAt,
		arg.Order,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RobotImage
	for rows.Next() {
		var i RobotImage
		if err := rows.Scan(
			&i.ID,
			&i.RobotID,
			&i.StorageKey,
			&i.ContentType,
			&i.DisplayKey,
			&i.DisplayContentType,
			&i.ThumbnailKey,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.CapturedAt,
			&i.ExifOrientation,
			&i.Caption,
			&i.UploaderID,
			&i.CreatedAt,
			&i.SortAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRobotPrimaryImage = `-- name: SetRobotPrimaryImage :exec
UPDATE robots SET primary_image_id = $1 WHERE id = $2
`

type SetRobotPrimaryImageParams struct {
	ImageID pgtype.UUID
	RobotID pgtype.UUID
}

func (q *Queries) SetRobotPrimaryImage(ctx context.Context, arg SetRobotPrimaryImageParams) error {
	_, err := q.db.Exec(ctx, setRobotPrimaryImage, arg.ImageID, arg.RobotID)
	return err
}

const updateRobotImage = `-- name: UpdateRobotImage :one
UPDATE robot_images
SET
    caption     = COALESCE($1,     caption),
    captured_at = CASE WHEN $2::bool
                       THEN $3
                       ELSE captured_at END
WHERE id = $4
RETURNING id, robot_id, storage_key, content_type, display_key, display_content_type, thumbnail_key, size_bytes, width, height, captured_at, exif_orientation, caption, uploader_id, created_at, sort_at
`

type UpdateRobotImageParams struct {
	Caption       *string
	CapturedAtSet bool
	CapturedAt    pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) UpdateRobotImage(ctx context.Context, arg UpdateRobotImageParams) (RobotImage, error) {
	row := q.db.QueryRow(ctx, updateRobotImage,
		arg.Caption,
		arg.CapturedAtSet,
		arg.CapturedAt,
		arg.ID,
	)
	var i RobotImage
	err := row.Scan(
		&i.ID,
		&i.RobotID,
		&i.StorageKey,
		&i.ContentType,
		&i.DisplayKey,
		&i.DisplayContentType,
		&i.ThumbnailKey,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.CapturedAt,
		&i.ExifOrientation,
		&i.Caption,
		&i.UploaderID,
		&i.CreatedAt,
		&i.SortAt,
	)
	return i, err
}
