// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_videos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRunVideo = `-- name: AddRunVideo :one
INSERT INTO run_videos (run_id, video_id, video_offset_start, video_offset_end, run_offset_sec, angle_label)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, video_id, video_offset_start, video_offset_end, angle_label, created_at, run_offset_sec
`

type AddRunVideoParams struct {
	RunID            pgtype.UUID
	VideoID          pgtype.UUID
	VideoOffsetStart int32
	VideoOffsetEnd   int32
	RunOffsetSec     int32
	AngleLabel       string
}

func (q *Queries) AddRunVideo(ctx context.Context, arg AddRunVideoParams) (RunVideo, error) {
	row := q.db.QueryRow(ctx, addRunVideo,
		arg.RunID,
		arg.VideoID,
		arg.VideoOffsetStart,
		arg.VideoOffsetEnd,
		arg.RunOffsetSec,
		arg.AngleLabel,
	)
	var i RunVideo
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.VideoID,
		&i.VideoOffsetStart,
		&i.VideoOffsetEnd,
		&i.AngleLabel,
		&i.CreatedAt,
		&i.RunOffsetSec,
	)
	return i, err
}

const deleteRunVideo = `-- name: DeleteRunVideo :execrows
DELETE FROM run_videos WHERE id = $1
`

func (q *Queries) DeleteRunVideo(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRunVideo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRunVideoByRunAndVideo = `-- name: DeleteRunVideoByRunAndVideo :execrows
DELETE FROM run_videos WHERE run_id = $1 AND video_id = $2
`

type DeleteRunVideoByRunAndVideoParams struct {
	RunID   pgtype.UUID
	VideoID pgtype.UUID
}

func (q *Queries) DeleteRunVideoByRunAndVideo(ctx context.Context, arg DeleteRunVideoByRunAndVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRunVideoByRunAndVideo, arg.RunID, arg.VideoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRunVideo = `-- name: GetRunVideo :one
SELECT id, run_id, video_id, video_offset_start, video_offset_end, angle_label, created_at, run_offset_sec FROM run_videos WHERE id = $1
`

func (q *Queries) GetRunVideo(ctx context.Context, id pgtype.UUID) (RunVideo, error) {
	row := q.db.QueryRow(ctx, getRunVideo, id)
	var i RunVideo
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.VideoID,
		&i.VideoOffsetStart,
		&i.VideoOffsetEnd,
		&i.AngleLabel,
		&i.CreatedAt,
		&i.RunOffsetSec,
	)
	return i, err
}

const listRunVideosByRun = `-- name: ListRunVideosByRun :many
SELECT id, run_id, video_id, video_offset_start, video_offset_end, angle_label, created_at, run_offset_sec FROM run_videos
WHERE run_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListRunVideosByRun(ctx context.Context, runID pgtype.UUID) ([]RunVideo, error) {
	rows, err := q.db.Query(ctx, listRunVideosByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunVideo
	for rows.Next() {
		var i RunVideo
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.VideoID,
			&i.VideoOffsetStart,
			&i.VideoOffsetEnd,
			&i.AngleLabel,
			&i.CreatedAt,
			&i.RunOffsetSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunVideo = `-- name: UpdateRunVideo :one
UPDATE run_videos
SET
  video_offset_start = COALESCE($1, video_offset_start),
  video_offset_end = COALESCE($2, video_offset_end),
  run_offset_sec = COALESCE($3, run_offset_sec),
  angle_label = COALESCE($4, angle_label)
WHERE id = $5
RETURNING id, run_id, video_id, video_offset_start, video_offset_end, angle_label, created_at, run_offset_sec
`

type UpdateRunVideoParams struct {
	VideoOffsetStart *int32
	VideoOffsetEnd   *int32
	RunOffsetSec     *int32
	AngleLabel       *string
	ID               pgtype.UUID
}

func (q *Queries) UpdateRunVideo(ctx context.Context, arg UpdateRunVideoParams) (RunVideo, error) {
	row := q.db.QueryRow(ctx, updateRunVideo,
		arg.VideoOffsetStart,
		arg.VideoOffsetEnd,
		arg.RunOffsetSec,
		arg.AngleLabel,
		arg.ID,
	)
	var i RunVideo
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.VideoID,
		&i.VideoOffsetStart,
		&i.VideoOffsetEnd,
		&i.AngleLabel,
		&i.CreatedAt,
		&i.RunOffsetSec,
	)
	return i, err
}
