// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRunTag = `-- name: AddRunTag :exec
INSERT INTO run_tags (run_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRunTagParams struct {
	RunID pgtype.UUID
	TagID pgtype.UUID
}

func (q *Queries) AddRunTag(ctx context.Context, arg AddRunTagParams) error {
	_, err := q.db.Exec(ctx, addRunTag, arg.RunID, arg.TagID)
	return err
}

const clearRunTags = `-- name: ClearRunTags :exec
DELETE FROM run_tags WHERE run_id = $1
`

func (q *Queries) ClearRunTags(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearRunTags, runID)
	return err
}

const listRunTagsByRun = `-- name: ListRunTagsByRun :many
SELECT tag_id FROM run_tags WHERE run_id = $1
`

func (q *Queries) ListRunTagsByRun(ctx context.Context, runID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRunTagsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var tag_id pgtype.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
