// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (tournament_id, session_id, team_id, robot_id, scenario_id, match_id, started_at, score, memo, duration_sec)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, session_id, team_id, robot_id, scenario_id, match_id, started_at, score, memo, created_at, duration_sec, tournament_id
`

type CreateRunParams struct {
	TournamentID pgtype.UUID
	SessionID    pgtype.UUID
	TeamID       pgtype.UUID
	RobotID      pgtype.UUID
	ScenarioID   pgtype.UUID
	MatchID      pgtype.UUID
	StartedAt    pgtype.Timestamptz
	Score        *float64
	Memo         string
	DurationSec  int32
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.TournamentID,
		arg.SessionID,
		arg.TeamID,
		arg.RobotID,
		arg.ScenarioID,
		arg.MatchID,
		arg.StartedAt,
		arg.Score,
		arg.Memo,
		arg.DurationSec,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TeamID,
		&i.RobotID,
		&i.ScenarioID,
		&i.MatchID,
		&i.StartedAt,
		&i.Score,
		&i.Memo,
		&i.CreatedAt,
		&i.DurationSec,
		&i.TournamentID,
	)
	return i, err
}

const deleteRun = `-- name: DeleteRun :execrows
DELETE FROM runs WHERE id = $1
`

func (q *Queries) DeleteRun(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRun = `-- name: GetRun :one
SELECT id, session_id, team_id, robot_id, scenario_id, match_id, started_at, score, memo, created_at, duration_sec, tournament_id FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TeamID,
		&i.RobotID,
		&i.ScenarioID,
		&i.MatchID,
		&i.StartedAt,
		&i.Score,
		&i.Memo,
		&i.CreatedAt,
		&i.DurationSec,
		&i.TournamentID,
	)
	return i, err
}

const listRecommendedVideosForRun = `-- name: ListRecommendedVideosForRun :many
SELECT v.id, v.session_id, v.device_id, v.uploader_id, v.storage_key, v.recorded_at, v.duration_sec, v.time_offset_sec, v.created_at, v.thumbnail_key, v.display_name, v.hls_master_key, v.hls_status, v.source_video_codec, v.source_audio_codec, v.source_width, v.source_height, v.passthrough_ok, v.tournament_id
FROM videos v
JOIN runs r ON r.id = $1
WHERE v.session_id = r.session_id
  AND NOT EXISTS (
    SELECT 1 FROM run_videos rv
    WHERE rv.run_id = r.id AND rv.video_id = v.id
  )
ORDER BY v.created_at DESC, v.id DESC
LIMIT 50
`

// Videos uploaded against the Run's session that are not yet attached to it.
// Used to populate the "Run に追加すべき動画" recommendation list.
func (q *Queries) ListRecommendedVideosForRun(ctx context.Context, id pgtype.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, listRecommendedVideosForRun, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DeviceID,
			&i.UploaderID,
			&i.StorageKey,
			&i.RecordedAt,
			&i.DurationSec,
			&i.TimeOffsetSec,
			&i.CreatedAt,
			&i.ThumbnailKey,
			&i.DisplayName,
			&i.HlsMasterKey,
			&i.HLSStatus,
			&i.SourceVideoCodec,
			&i.SourceAudioCodec,
			&i.SourceWidth,
			&i.SourceHeight,
			&i.PassthroughOk,
			&i.TournamentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsPage = `-- name: ListRunsPage :many
SELECT id, session_id, team_id, robot_id, scenario_id, match_id, started_at, score, memo, created_at, duration_sec, tournament_id
FROM runs
WHERE
  tournament_id = $2::uuid
  AND ($3::uuid IS NULL OR session_id = $3::uuid)
  AND ($4::uuid IS NULL OR team_id = $4::uuid)
  AND ($5::uuid IS NULL OR robot_id = $5::uuid)
  AND ($6::uuid IS NULL OR scenario_id = $6::uuid)
  AND ($7::uuid IS NULL OR match_id = $7::uuid)
  AND ($8::timestamptz IS NULL OR (created_at, id) > ($8::timestamptz, $9::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $1
`

type ListRunsPageParams struct {
	Limit           int32
	TournamentID    pgtype.UUID
	SessionID       pgtype.UUID
	TeamID          pgtype.UUID
	RobotID         pgtype.UUID
	ScenarioID      pgtype.UUID
	MatchID         pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListRunsPage(ctx context.Context, arg ListRunsPageParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsPage,
		arg.Limit,
		arg.TournamentID,
		arg.SessionID,
		arg.TeamID,
		arg.RobotID,
		arg.ScenarioID,
		arg.MatchID,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TeamID,
			&i.RobotID,
			&i.ScenarioID,
			&i.MatchID,
			&i.StartedAt,
			&i.Score,
			&i.Memo,
			&i.CreatedAt,
			&i.DurationSec,
			&i.TournamentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRuns = `-- name: SearchRuns :many
SELECT r.id, r.session_id, r.team_id, r.robot_id, r.scenario_id, r.match_id, r.started_at, r.score, r.memo, r.created_at, r.duration_sec, r.tournament_id
FROM runs r
WHERE
  r.tournament_id = $2::uuid
  AND ($3::timestamptz IS NULL OR r.started_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR r.started_at < $4::timestamptz)
  AND ($5::uuid IS NULL OR r.robot_id = $5::uuid)
  AND ($6::uuid IS NULL OR r.scenario_id = $6::uuid)
  AND ($7::text IS NULL OR r.memo ILIKE '%' || $7::text || '%')
  AND (COALESCE(array_length($8::text[], 1), 0) = 0
       OR EXISTS (
         SELECT 1 FROM markers m
         WHERE m.run_id = r.id
           AND m.category::text = ANY($8::text[])
       ))
  AND ($9::int = 0 OR (
         SELECT count(DISTINCT tag_id) FROM run_tags
         WHERE run_id = r.id
           AND tag_id = ANY($10::uuid[])
       ) = $9::int)
  AND ($11::timestamptz IS NULL
       OR (r.started_at, r.id) < ($11::timestamptz, $12::uuid))
ORDER BY r.started_at DESC, r.id DESC
LIMIT $1
`

type SearchRunsParams struct {
	Limit            int32
	TournamentID     pgtype.UUID
	From             pgtype.Timestamptz
	To               pgtype.Timestamptz
	RobotID          pgtype.UUID
	ScenarioID       pgtype.UUID
	MemoQ            *string
	MarkerCategories []string
	TagCount         int32
	TagIds           []pgtype.UUID
	CursorStartedAt  pgtype.Timestamptz
	CursorID         pgtype.UUID
}

func (q *Queries) SearchRuns(ctx context.Context, arg SearchRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, searchRuns,
		arg.Limit,
		arg.TournamentID,
		arg.From,
		arg.To,
		arg.RobotID,
		arg.ScenarioID,
		arg.MemoQ,
		arg.MarkerCategories,
		arg.TagCount,
		arg.TagIds,
		arg.CursorStartedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TeamID,
			&i.RobotID,
			&i.ScenarioID,
			&i.MatchID,
			&i.StartedAt,
			&i.Score,
			&i.Memo,
			&i.CreatedAt,
			&i.DurationSec,
			&i.TournamentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRun = `-- name: UpdateRun :one
UPDATE runs
SET
  robot_id = COALESCE($1::uuid, robot_id),
  scenario_id = COALESCE($2::uuid, scenario_id),
  match_id = CASE WHEN $3::bool THEN $4::uuid ELSE match_id END,
  started_at = COALESCE($5::timestamptz, started_at),
  score = CASE WHEN $6::bool THEN $7::float8 ELSE score END,
  memo = COALESCE($8, memo),
  duration_sec = COALESCE($9::int, duration_sec)
WHERE id = $10
RETURNING id, session_id, team_id, robot_id, scenario_id, match_id, started_at, score, memo, created_at, duration_sec, tournament_id
`

type UpdateRunParams struct {
	RobotID     pgtype.UUID
	ScenarioID  pgtype.UUID
	MatchIDSet  bool
	MatchID     pgtype.UUID
	StartedAt   pgtype.Timestamptz
	ScoreSet    bool
	Score       *float64
	Memo        *string
	DurationSec *int32
	ID          pgtype.UUID
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRun,
		arg.RobotID,
		arg.ScenarioID,
		arg.MatchIDSet,
		arg.MatchID,
		arg.StartedAt,
		arg.ScoreSet,
		arg.Score,
		arg.Memo,
		arg.DurationSec,
		arg.ID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TeamID,
		&i.RobotID,
		&i.ScenarioID,
		&i.MatchID,
		&i.StartedAt,
		&i.Score,
		&i.Memo,
		&i.CreatedAt,
		&i.DurationSec,
		&i.TournamentID,
	)
	return i, err
}
