// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (session_id, team_id, robot_id, scenario_id, match_id, started_at, ended_at, score, memo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, session_id, team_id, robot_id, scenario_id, match_id, started_at, ended_at, score, memo, created_at
`

type CreateRunParams struct {
	SessionID  pgtype.UUID
	TeamID     pgtype.UUID
	RobotID    pgtype.UUID
	ScenarioID pgtype.UUID
	MatchID    pgtype.UUID
	StartedAt  pgtype.Timestamptz
	EndedAt    pgtype.Timestamptz
	Score      *float64
	Memo       string
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.SessionID,
		arg.TeamID,
		arg.RobotID,
		arg.ScenarioID,
		arg.MatchID,
		arg.StartedAt,
		arg.EndedAt,
		arg.Score,
		arg.Memo,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TeamID,
		&i.RobotID,
		&i.ScenarioID,
		&i.MatchID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Score,
		&i.Memo,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRun = `-- name: DeleteRun :execrows
DELETE FROM runs WHERE id = $1
`

func (q *Queries) DeleteRun(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRun = `-- name: GetRun :one
SELECT id, session_id, team_id, robot_id, scenario_id, match_id, started_at, ended_at, score, memo, created_at FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TeamID,
		&i.RobotID,
		&i.ScenarioID,
		&i.MatchID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Score,
		&i.Memo,
		&i.CreatedAt,
	)
	return i, err
}

const listRunsPage = `-- name: ListRunsPage :many
SELECT id, session_id, team_id, robot_id, scenario_id, match_id, started_at, ended_at, score, memo, created_at
FROM runs
WHERE
  ($2::uuid IS NULL OR session_id = $2::uuid)
  AND ($3::uuid IS NULL OR team_id = $3::uuid)
  AND ($4::uuid IS NULL OR robot_id = $4::uuid)
  AND ($5::uuid IS NULL OR scenario_id = $5::uuid)
  AND ($6::uuid IS NULL OR match_id = $6::uuid)
  AND ($7::timestamptz IS NULL OR (created_at, id) > ($7::timestamptz, $8::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $1
`

type ListRunsPageParams struct {
	Limit           int32
	SessionID       pgtype.UUID
	TeamID          pgtype.UUID
	RobotID         pgtype.UUID
	ScenarioID      pgtype.UUID
	MatchID         pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListRunsPage(ctx context.Context, arg ListRunsPageParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsPage,
		arg.Limit,
		arg.SessionID,
		arg.TeamID,
		arg.RobotID,
		arg.ScenarioID,
		arg.MatchID,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TeamID,
			&i.RobotID,
			&i.ScenarioID,
			&i.MatchID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Score,
			&i.Memo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRun = `-- name: UpdateRun :one
UPDATE runs
SET
  robot_id = COALESCE($1::uuid, robot_id),
  scenario_id = COALESCE($2::uuid, scenario_id),
  match_id = CASE WHEN $3::bool THEN $4::uuid ELSE match_id END,
  started_at = COALESCE($5::timestamptz, started_at),
  ended_at = COALESCE($6::timestamptz, ended_at),
  score = CASE WHEN $7::bool THEN $8::float8 ELSE score END,
  memo = COALESCE($9, memo)
WHERE id = $10
RETURNING id, session_id, team_id, robot_id, scenario_id, match_id, started_at, ended_at, score, memo, created_at
`

type UpdateRunParams struct {
	RobotID    pgtype.UUID
	ScenarioID pgtype.UUID
	MatchIDSet bool
	MatchID    pgtype.UUID
	StartedAt  pgtype.Timestamptz
	EndedAt    pgtype.Timestamptz
	ScoreSet   bool
	Score      *float64
	Memo       *string
	ID         pgtype.UUID
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRun,
		arg.RobotID,
		arg.ScenarioID,
		arg.MatchIDSet,
		arg.MatchID,
		arg.StartedAt,
		arg.EndedAt,
		arg.ScoreSet,
		arg.Score,
		arg.Memo,
		arg.ID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TeamID,
		&i.RobotID,
		&i.ScenarioID,
		&i.MatchID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Score,
		&i.Memo,
		&i.CreatedAt,
	)
	return i, err
}
