// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenarios.sql

package sqlc

import (
	"context"
)

const createScenario = `-- name: CreateScenario :one
INSERT INTO scenarios (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at
`

type CreateScenarioParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (Scenario, error) {
	row := q.db.QueryRow(ctx, createScenario, arg.Name, arg.Description)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listScenarios = `-- name: ListScenarios :many
SELECT id, name, description, created_at FROM scenarios ORDER BY name ASC
`

func (q *Queries) ListScenarios(ctx context.Context) ([]Scenario, error) {
	rows, err := q.db.Query(ctx, listScenarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scenario
	for rows.Next() {
		var i Scenario
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
