// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scouting_notes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScoutingNote = `-- name: CreateScoutingNote :one

INSERT INTO scouting_notes (tournament_id, team_id)
VALUES ($1, $2)
RETURNING id, ydoc_state, plain_text, updated_at, created_at, tournament_id, team_id
`

type CreateScoutingNoteParams struct {
	TournamentID pgtype.UUID
	TeamID       pgtype.UUID
}

// ScoutingNote rows: ydoc_state / plain_text は Hocuspocus が更新するため
// Go API は CRUD と GET だけを公開する。
// (tournament_id, team_id) ごとに最大1行。
func (q *Queries) CreateScoutingNote(ctx context.Context, arg CreateScoutingNoteParams) (ScoutingNote, error) {
	row := q.db.QueryRow(ctx, createScoutingNote, arg.TournamentID, arg.TeamID)
	var i ScoutingNote
	err := row.Scan(
		&i.ID,
		&i.YdocState,
		&i.PlainText,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TournamentID,
		&i.TeamID,
	)
	return i, err
}

const deleteScoutingNote = `-- name: DeleteScoutingNote :execrows
DELETE FROM scouting_notes WHERE id = $1
`

func (q *Queries) DeleteScoutingNote(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScoutingNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScoutingNote = `-- name: GetScoutingNote :one
SELECT id, ydoc_state, plain_text, updated_at, created_at, tournament_id, team_id FROM scouting_notes WHERE id = $1
`

func (q *Queries) GetScoutingNote(ctx context.Context, id pgtype.UUID) (ScoutingNote, error) {
	row := q.db.QueryRow(ctx, getScoutingNote, id)
	var i ScoutingNote
	err := row.Scan(
		&i.ID,
		&i.YdocState,
		&i.PlainText,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TournamentID,
		&i.TeamID,
	)
	return i, err
}

const getScoutingNoteByTournamentAndTeam = `-- name: GetScoutingNoteByTournamentAndTeam :one
SELECT id, ydoc_state, plain_text, updated_at, created_at, tournament_id, team_id FROM scouting_notes
WHERE tournament_id = $1 AND team_id = $2
`

type GetScoutingNoteByTournamentAndTeamParams struct {
	TournamentID pgtype.UUID
	TeamID       pgtype.UUID
}

func (q *Queries) GetScoutingNoteByTournamentAndTeam(ctx context.Context, arg GetScoutingNoteByTournamentAndTeamParams) (ScoutingNote, error) {
	row := q.db.QueryRow(ctx, getScoutingNoteByTournamentAndTeam, arg.TournamentID, arg.TeamID)
	var i ScoutingNote
	err := row.Scan(
		&i.ID,
		&i.YdocState,
		&i.PlainText,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.TournamentID,
		&i.TeamID,
	)
	return i, err
}

const listScoutingNotesByTournament = `-- name: ListScoutingNotesByTournament :many
SELECT id, ydoc_state, plain_text, updated_at, created_at, tournament_id, team_id FROM scouting_notes
WHERE tournament_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListScoutingNotesByTournament(ctx context.Context, tournamentID pgtype.UUID) ([]ScoutingNote, error) {
	rows, err := q.db.Query(ctx, listScoutingNotesByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoutingNote
	for rows.Next() {
		var i ScoutingNote
		if err := rows.Scan(
			&i.ID,
			&i.YdocState,
			&i.PlainText,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.TournamentID,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
