// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scouting_notes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScoutingNote = `-- name: CreateScoutingNote :one

INSERT INTO scouting_notes (match_id, target_team_id)
VALUES ($1, $2)
RETURNING id, match_id, target_team_id, ydoc_state, plain_text, updated_at, created_at
`

type CreateScoutingNoteParams struct {
	MatchID      pgtype.UUID
	TargetTeamID pgtype.UUID
}

// ScoutingNote rows: ydoc_state / plain_text は Hocuspocus が更新するため
// Go API は CRUD と GET だけを公開する。
func (q *Queries) CreateScoutingNote(ctx context.Context, arg CreateScoutingNoteParams) (ScoutingNote, error) {
	row := q.db.QueryRow(ctx, createScoutingNote, arg.MatchID, arg.TargetTeamID)
	var i ScoutingNote
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TargetTeamID,
		&i.YdocState,
		&i.PlainText,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteScoutingNote = `-- name: DeleteScoutingNote :execrows
DELETE FROM scouting_notes WHERE id = $1
`

func (q *Queries) DeleteScoutingNote(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScoutingNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScoutingNote = `-- name: GetScoutingNote :one
SELECT id, match_id, target_team_id, ydoc_state, plain_text, updated_at, created_at FROM scouting_notes WHERE id = $1
`

func (q *Queries) GetScoutingNote(ctx context.Context, id pgtype.UUID) (ScoutingNote, error) {
	row := q.db.QueryRow(ctx, getScoutingNote, id)
	var i ScoutingNote
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TargetTeamID,
		&i.YdocState,
		&i.PlainText,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getScoutingNoteByMatchAndTeam = `-- name: GetScoutingNoteByMatchAndTeam :one
SELECT id, match_id, target_team_id, ydoc_state, plain_text, updated_at, created_at FROM scouting_notes
WHERE match_id = $1 AND target_team_id = $2
`

type GetScoutingNoteByMatchAndTeamParams struct {
	MatchID      pgtype.UUID
	TargetTeamID pgtype.UUID
}

func (q *Queries) GetScoutingNoteByMatchAndTeam(ctx context.Context, arg GetScoutingNoteByMatchAndTeamParams) (ScoutingNote, error) {
	row := q.db.QueryRow(ctx, getScoutingNoteByMatchAndTeam, arg.MatchID, arg.TargetTeamID)
	var i ScoutingNote
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TargetTeamID,
		&i.YdocState,
		&i.PlainText,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listScoutingNotesByMatch = `-- name: ListScoutingNotesByMatch :many
SELECT id, match_id, target_team_id, ydoc_state, plain_text, updated_at, created_at FROM scouting_notes
WHERE match_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListScoutingNotesByMatch(ctx context.Context, matchID pgtype.UUID) ([]ScoutingNote, error) {
	rows, err := q.db.Query(ctx, listScoutingNotesByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoutingNote
	for rows.Next() {
		var i ScoutingNote
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.TargetTeamID,
			&i.YdocState,
			&i.PlainText,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
