// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (name, started_at, ended_at, location, mode_hint, tournament_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, started_at, ended_at, location, mode_hint, tournament_id, created_at
`

type CreateSessionParams struct {
	Name         string
	StartedAt    pgtype.Timestamptz
	EndedAt      pgtype.Timestamptz
	Location     *string
	ModeHint     SessionModeHint
	TournamentID pgtype.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Name,
		arg.StartedAt,
		arg.EndedAt,
		arg.Location,
		arg.ModeHint,
		arg.TournamentID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartedAt,
		&i.EndedAt,
		&i.Location,
		&i.ModeHint,
		&i.TournamentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSession = `-- name: GetSession :one
SELECT id, name, started_at, ended_at, location, mode_hint, tournament_id, created_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartedAt,
		&i.EndedAt,
		&i.Location,
		&i.ModeHint,
		&i.TournamentID,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionsPage = `-- name: ListSessionsPage :many
SELECT id, name, started_at, ended_at, location, mode_hint, tournament_id, created_at
FROM sessions
WHERE
  ($2::session_mode_hint IS NULL OR mode_hint = $2::session_mode_hint)
  AND ($3::uuid IS NULL OR tournament_id = $3::uuid)
  AND ($4::timestamptz IS NULL OR started_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR started_at <= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR (created_at, id) > ($6::timestamptz, $7::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $1
`

type ListSessionsPageParams struct {
	Limit           int32
	ModeHint        NullSessionModeHint
	TournamentID    pgtype.UUID
	StartedFrom     pgtype.Timestamptz
	StartedTo       pgtype.Timestamptz
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListSessionsPage(ctx context.Context, arg ListSessionsPageParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsPage,
		arg.Limit,
		arg.ModeHint,
		arg.TournamentID,
		arg.StartedFrom,
		arg.StartedTo,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartedAt,
			&i.EndedAt,
			&i.Location,
			&i.ModeHint,
			&i.TournamentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
  name = COALESCE($1, name),
  started_at = CASE WHEN $2::bool THEN $3 ELSE started_at END,
  ended_at = CASE WHEN $4::bool THEN $5 ELSE ended_at END,
  location = CASE WHEN $6::bool THEN $7 ELSE location END,
  mode_hint = COALESCE($8::session_mode_hint, mode_hint),
  tournament_id = CASE WHEN $9::bool THEN $10::uuid ELSE tournament_id END
WHERE id = $11
RETURNING id, name, started_at, ended_at, location, mode_hint, tournament_id, created_at
`

type UpdateSessionParams struct {
	Name            *string
	StartedAtSet    bool
	StartedAt       pgtype.Timestamptz
	EndedAtSet      bool
	EndedAt         pgtype.Timestamptz
	LocationSet     bool
	Location        *string
	ModeHint        NullSessionModeHint
	TournamentIDSet bool
	TournamentID    pgtype.UUID
	ID              pgtype.UUID
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.Name,
		arg.StartedAtSet,
		arg.StartedAt,
		arg.EndedAtSet,
		arg.EndedAt,
		arg.LocationSet,
		arg.Location,
		arg.ModeHint,
		arg.TournamentIDSet,
		arg.TournamentID,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartedAt,
		&i.EndedAt,
		&i.Location,
		&i.ModeHint,
		&i.TournamentID,
		&i.CreatedAt,
	)
	return i, err
}
