// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlc

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, is_own)
VALUES ($1, $2)
RETURNING id, name, is_own, created_at
`

type CreateTeamParams struct {
	Name  string
	IsOwn bool
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.IsOwn)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsOwn,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnTeam = `-- name: GetOwnTeam :one
SELECT id, name, is_own, created_at FROM teams WHERE is_own LIMIT 1
`

func (q *Queries) GetOwnTeam(ctx context.Context) (Team, error) {
	row := q.db.QueryRow(ctx, getOwnTeam)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsOwn,
		&i.CreatedAt,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, is_own, created_at FROM teams ORDER BY is_own DESC, name ASC
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsOwn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
