// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournaments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTournamentRobot = `-- name: AddTournamentRobot :exec
INSERT INTO tournament_robots (tournament_id, robot_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTournamentRobotParams struct {
	TournamentID pgtype.UUID
	RobotID      pgtype.UUID
}

func (q *Queries) AddTournamentRobot(ctx context.Context, arg AddTournamentRobotParams) error {
	_, err := q.db.Exec(ctx, addTournamentRobot, arg.TournamentID, arg.RobotID)
	return err
}

const addTournamentTeam = `-- name: AddTournamentTeam :exec
INSERT INTO tournament_teams (tournament_id, team_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTournamentTeamParams struct {
	TournamentID pgtype.UUID
	TeamID       pgtype.UUID
}

func (q *Queries) AddTournamentTeam(ctx context.Context, arg AddTournamentTeamParams) error {
	_, err := q.db.Exec(ctx, addTournamentTeam, arg.TournamentID, arg.TeamID)
	return err
}

const clearTournamentRobots = `-- name: ClearTournamentRobots :exec
DELETE FROM tournament_robots WHERE tournament_id = $1
`

func (q *Queries) ClearTournamentRobots(ctx context.Context, tournamentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTournamentRobots, tournamentID)
	return err
}

const clearTournamentTeams = `-- name: ClearTournamentTeams :exec
DELETE FROM tournament_teams WHERE tournament_id = $1
`

func (q *Queries) ClearTournamentTeams(ctx context.Context, tournamentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTournamentTeams, tournamentID)
	return err
}

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (name, start_date, end_date)
VALUES ($1, $2, $3)
RETURNING id, name, start_date, end_date, created_at
`

type CreateTournamentParams struct {
	Name      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, createTournament, arg.Name, arg.StartDate, arg.EndDate)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTournament = `-- name: DeleteTournament :execrows
DELETE FROM tournaments WHERE id = $1
`

func (q *Queries) DeleteTournament(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTournament, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTournament = `-- name: GetTournament :one
SELECT id, name, start_date, end_date, created_at FROM tournaments WHERE id = $1
`

func (q *Queries) GetTournament(ctx context.Context, id pgtype.UUID) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournament, id)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const listRobotsByTournament = `-- name: ListRobotsByTournament :many
SELECT r.id, r.team_id, r.name, r.version, r.created_at, r.primary_image_id
FROM tournament_robots tr
JOIN robots r ON r.id = tr.robot_id
WHERE tr.tournament_id = $1
ORDER BY r.name ASC, r.version ASC
`

func (q *Queries) ListRobotsByTournament(ctx context.Context, tournamentID pgtype.UUID) ([]Robot, error) {
	rows, err := q.db.Query(ctx, listRobotsByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Robot
	for rows.Next() {
		var i Robot
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.PrimaryImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByTournament = `-- name: ListTeamsByTournament :many

SELECT t.id, t.name, t.is_own, t.created_at
FROM tournament_teams tt
JOIN teams t ON t.id = tt.team_id
WHERE tt.tournament_id = $1
ORDER BY t.is_own DESC, t.name ASC
`

// ---------- Tournament <-> Team / Robot links (P0) ----------
func (q *Queries) ListTeamsByTournament(ctx context.Context, tournamentID pgtype.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsOwn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentRobotsTeamIDs = `-- name: ListTournamentRobotsTeamIDs :many
SELECT id, team_id
FROM robots
WHERE id = ANY($1::uuid[])
`

type ListTournamentRobotsTeamIDsRow struct {
	ID     pgtype.UUID
	TeamID pgtype.UUID
}

// 整合性チェック用: PUT /tournaments/{id}/robots で渡された各 robot の team_id が
// 大会の参加チームに含まれているかを検証するために、対象 robot_ids の team_id を一括取得する。
func (q *Queries) ListTournamentRobotsTeamIDs(ctx context.Context, robotIds []pgtype.UUID) ([]ListTournamentRobotsTeamIDsRow, error) {
	rows, err := q.db.Query(ctx, listTournamentRobotsTeamIDs, robotIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTournamentRobotsTeamIDsRow
	for rows.Next() {
		var i ListTournamentRobotsTeamIDsRow
		if err := rows.Scan(&i.ID, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentsPage = `-- name: ListTournamentsPage :many
SELECT id, name, start_date, end_date, created_at
FROM tournaments
WHERE ($2::timestamptz IS NULL
       OR (created_at, id) > ($2::timestamptz, $3::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $1
`

type ListTournamentsPageParams struct {
	Limit           int32
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListTournamentsPage(ctx context.Context, arg ListTournamentsPageParams) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, listTournamentsPage, arg.Limit, arg.CursorCreatedAt, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTournamentRobot = `-- name: RemoveTournamentRobot :execrows
DELETE FROM tournament_robots
WHERE tournament_id = $1 AND robot_id = $2
`

type RemoveTournamentRobotParams struct {
	TournamentID pgtype.UUID
	RobotID      pgtype.UUID
}

func (q *Queries) RemoveTournamentRobot(ctx context.Context, arg RemoveTournamentRobotParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTournamentRobot, arg.TournamentID, arg.RobotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeTournamentTeam = `-- name: RemoveTournamentTeam :execrows
DELETE FROM tournament_teams
WHERE tournament_id = $1 AND team_id = $2
`

type RemoveTournamentTeamParams struct {
	TournamentID pgtype.UUID
	TeamID       pgtype.UUID
}

func (q *Queries) RemoveTournamentTeam(ctx context.Context, arg RemoveTournamentTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTournamentTeam, arg.TournamentID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTournament = `-- name: UpdateTournament :one
UPDATE tournaments
SET
  name       = COALESCE($1, name),
  start_date = CASE WHEN $2::bool THEN $3::date ELSE start_date END,
  end_date   = CASE WHEN $4::bool THEN $5::date ELSE end_date END
WHERE id = $6
RETURNING id, name, start_date, end_date, created_at
`

type UpdateTournamentParams struct {
	Name         *string
	StartDateSet bool
	StartDate    pgtype.Date
	EndDateSet   bool
	EndDate      pgtype.Date
	ID           pgtype.UUID
}

func (q *Queries) UpdateTournament(ctx context.Context, arg UpdateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, updateTournament,
		arg.Name,
		arg.StartDateSet,
		arg.StartDate,
		arg.EndDateSet,
		arg.EndDate,
		arg.ID,
	)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}
