// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tournaments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (name, start_date, end_date)
VALUES ($1, $2, $3)
RETURNING id, name, start_date, end_date, created_at
`

type CreateTournamentParams struct {
	Name      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, createTournament, arg.Name, arg.StartDate, arg.EndDate)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTournament = `-- name: DeleteTournament :execrows
DELETE FROM tournaments WHERE id = $1
`

func (q *Queries) DeleteTournament(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTournament, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTournament = `-- name: GetTournament :one
SELECT id, name, start_date, end_date, created_at FROM tournaments WHERE id = $1
`

func (q *Queries) GetTournament(ctx context.Context, id pgtype.UUID) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournament, id)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const listTournamentsPage = `-- name: ListTournamentsPage :many
SELECT id, name, start_date, end_date, created_at
FROM tournaments
WHERE ($2::timestamptz IS NULL
       OR (created_at, id) > ($2::timestamptz, $3::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $1
`

type ListTournamentsPageParams struct {
	Limit           int32
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListTournamentsPage(ctx context.Context, arg ListTournamentsPageParams) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, listTournamentsPage, arg.Limit, arg.CursorCreatedAt, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTournament = `-- name: UpdateTournament :one
UPDATE tournaments
SET
  name       = COALESCE($1, name),
  start_date = CASE WHEN $2::bool THEN $3::date ELSE start_date END,
  end_date   = CASE WHEN $4::bool THEN $5::date ELSE end_date END
WHERE id = $6
RETURNING id, name, start_date, end_date, created_at
`

type UpdateTournamentParams struct {
	Name         *string
	StartDateSet bool
	StartDate    pgtype.Date
	EndDateSet   bool
	EndDate      pgtype.Date
	ID           pgtype.UUID
}

func (q *Queries) UpdateTournament(ctx context.Context, arg UpdateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, updateTournament,
		arg.Name,
		arg.StartDateSet,
		arg.StartDate,
		arg.EndDateSet,
		arg.EndDate,
		arg.ID,
	)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}
