// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, color)
VALUES ($1, $2)
RETURNING id, name, color, created_at, oidc_sub, email
`

type CreateUserParams struct {
	Name  string
	Color *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Color)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.OidcSub,
		&i.Email,
	)
	return i, err
}

const createUserFromOIDC = `-- name: CreateUserFromOIDC :one
INSERT INTO users (name, oidc_sub, email)
VALUES ($1, $2, $3)
RETURNING id, name, color, created_at, oidc_sub, email
`

type CreateUserFromOIDCParams struct {
	Name    string
	OidcSub *string
	Email   *string
}

func (q *Queries) CreateUserFromOIDC(ctx context.Context, arg CreateUserFromOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserFromOIDC, arg.Name, arg.OidcSub, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.OidcSub,
		&i.Email,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, color, created_at, oidc_sub, email FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.OidcSub,
		&i.Email,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, color, created_at, oidc_sub, email FROM users WHERE lower(email) = lower($1::text)
`

func (q *Queries) GetUserByEmail(ctx context.Context, dollar_1 string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, dollar_1)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.OidcSub,
		&i.Email,
	)
	return i, err
}

const getUserByOIDCSub = `-- name: GetUserByOIDCSub :one
SELECT id, name, color, created_at, oidc_sub, email FROM users WHERE oidc_sub = $1
`

func (q *Queries) GetUserByOIDCSub(ctx context.Context, oidcSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCSub, oidcSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.OidcSub,
		&i.Email,
	)
	return i, err
}

const linkUserOIDC = `-- name: LinkUserOIDC :one
UPDATE users
SET oidc_sub = $1::text,
    email    = COALESCE($2::text, email),
    name     = COALESCE($3::text, name)
WHERE id = $4::uuid
RETURNING id, name, color, created_at, oidc_sub, email
`

type LinkUserOIDCParams struct {
	OidcSub string
	Email   *string
	Name    *string
	ID      pgtype.UUID
}

func (q *Queries) LinkUserOIDC(ctx context.Context, arg LinkUserOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, linkUserOIDC,
		arg.OidcSub,
		arg.Email,
		arg.Name,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.OidcSub,
		&i.Email,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, color, created_at, oidc_sub, email FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.OidcSub,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPage = `-- name: ListUsersPage :many
SELECT id, name, color, created_at, oidc_sub, email
FROM users
WHERE ($2::timestamptz IS NULL OR (created_at, id) > ($2::timestamptz, $3::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $1
`

type ListUsersPageParams struct {
	Limit           int32
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersPage, arg.Limit, arg.CursorCreatedAt, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.OidcSub,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  name = COALESCE($1, name),
  color = CASE WHEN $2::bool THEN $3 ELSE color END
WHERE id = $4
RETURNING id, name, color, created_at, oidc_sub, email
`

type UpdateUserParams struct {
	Name     *string
	ColorSet bool
	Color    *string
	ID       pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.ColorSet,
		arg.Color,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.OidcSub,
		&i.Email,
	)
	return i, err
}
