// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (tournament_id, session_id, device_id, uploader_id, storage_key, display_name, recorded_at, duration_sec, time_offset_sec)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, session_id, device_id, uploader_id, storage_key, recorded_at, duration_sec, time_offset_sec, created_at, thumbnail_key, display_name, hls_master_key, hls_status, source_video_codec, source_audio_codec, source_width, source_height, passthrough_ok, tournament_id
`

type CreateVideoParams struct {
	TournamentID  pgtype.UUID
	SessionID     pgtype.UUID
	DeviceID      pgtype.UUID
	UploaderID    pgtype.UUID
	StorageKey    string
	DisplayName   string
	RecordedAt    pgtype.Timestamptz
	DurationSec   *int32
	TimeOffsetSec int32
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.TournamentID,
		arg.SessionID,
		arg.DeviceID,
		arg.UploaderID,
		arg.StorageKey,
		arg.DisplayName,
		arg.RecordedAt,
		arg.DurationSec,
		arg.TimeOffsetSec,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DeviceID,
		&i.UploaderID,
		&i.StorageKey,
		&i.RecordedAt,
		&i.DurationSec,
		&i.TimeOffsetSec,
		&i.CreatedAt,
		&i.ThumbnailKey,
		&i.DisplayName,
		&i.HlsMasterKey,
		&i.HLSStatus,
		&i.SourceVideoCodec,
		&i.SourceAudioCodec,
		&i.SourceWidth,
		&i.SourceHeight,
		&i.PassthroughOk,
		&i.TournamentID,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :execrows
DELETE FROM videos WHERE id = $1
`

func (q *Queries) DeleteVideo(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVideo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVideo = `-- name: GetVideo :one
SELECT id, session_id, device_id, uploader_id, storage_key, recorded_at, duration_sec, time_offset_sec, created_at, thumbnail_key, display_name, hls_master_key, hls_status, source_video_codec, source_audio_codec, source_width, source_height, passthrough_ok, tournament_id FROM videos WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DeviceID,
		&i.UploaderID,
		&i.StorageKey,
		&i.RecordedAt,
		&i.DurationSec,
		&i.TimeOffsetSec,
		&i.CreatedAt,
		&i.ThumbnailKey,
		&i.DisplayName,
		&i.HlsMasterKey,
		&i.HLSStatus,
		&i.SourceVideoCodec,
		&i.SourceAudioCodec,
		&i.SourceWidth,
		&i.SourceHeight,
		&i.PassthroughOk,
		&i.TournamentID,
	)
	return i, err
}

const getVideoByStorageKey = `-- name: GetVideoByStorageKey :one
SELECT id, session_id, device_id, uploader_id, storage_key, recorded_at, duration_sec, time_offset_sec, created_at, thumbnail_key, display_name, hls_master_key, hls_status, source_video_codec, source_audio_codec, source_width, source_height, passthrough_ok, tournament_id FROM videos WHERE storage_key = $1
`

func (q *Queries) GetVideoByStorageKey(ctx context.Context, storageKey string) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByStorageKey, storageKey)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DeviceID,
		&i.UploaderID,
		&i.StorageKey,
		&i.RecordedAt,
		&i.DurationSec,
		&i.TimeOffsetSec,
		&i.CreatedAt,
		&i.ThumbnailKey,
		&i.DisplayName,
		&i.HlsMasterKey,
		&i.HLSStatus,
		&i.SourceVideoCodec,
		&i.SourceAudioCodec,
		&i.SourceWidth,
		&i.SourceHeight,
		&i.PassthroughOk,
		&i.TournamentID,
	)
	return i, err
}

const listVideosPage = `-- name: ListVideosPage :many
SELECT id, session_id, device_id, uploader_id, storage_key, recorded_at, duration_sec, time_offset_sec, created_at, thumbnail_key, display_name, hls_master_key, hls_status, source_video_codec, source_audio_codec, source_width, source_height, passthrough_ok, tournament_id
FROM videos
WHERE
  tournament_id = $2::uuid
  AND ($3::uuid IS NULL OR session_id = $3::uuid)
  AND ($4::uuid IS NULL OR device_id = $4::uuid)
  AND ($5::bool IS NULL OR $5::bool = false OR session_id IS NULL)
  AND ($6::timestamptz IS NULL OR (created_at, id) > ($6::timestamptz, $7::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $1
`

type ListVideosPageParams struct {
	Limit           int32
	TournamentID    pgtype.UUID
	SessionID       pgtype.UUID
	DeviceID        pgtype.UUID
	Unassigned      *bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListVideosPage(ctx context.Context, arg ListVideosPageParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosPage,
		arg.Limit,
		arg.TournamentID,
		arg.SessionID,
		arg.DeviceID,
		arg.Unassigned,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DeviceID,
			&i.UploaderID,
			&i.StorageKey,
			&i.RecordedAt,
			&i.DurationSec,
			&i.TimeOffsetSec,
			&i.CreatedAt,
			&i.ThumbnailKey,
			&i.DisplayName,
			&i.HlsMasterKey,
			&i.HLSStatus,
			&i.SourceVideoCodec,
			&i.SourceAudioCodec,
			&i.SourceWidth,
			&i.SourceHeight,
			&i.PassthroughOk,
			&i.TournamentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos
SET
  session_id = CASE WHEN $1::bool THEN $2::uuid ELSE session_id END,
  tournament_id = COALESCE($3::uuid, tournament_id),
  device_id = CASE WHEN $4::bool THEN $5::uuid ELSE device_id END,
  recorded_at = CASE WHEN $6::bool THEN $7::timestamptz ELSE recorded_at END,
  time_offset_sec = COALESCE($8, time_offset_sec),
  display_name = COALESCE($9, display_name)
WHERE id = $10
RETURNING id, session_id, device_id, uploader_id, storage_key, recorded_at, duration_sec, time_offset_sec, created_at, thumbnail_key, display_name, hls_master_key, hls_status, source_video_codec, source_audio_codec, source_width, source_height, passthrough_ok, tournament_id
`

type UpdateVideoParams struct {
	SessionIDSet  bool
	SessionID     pgtype.UUID
	TournamentID  pgtype.UUID
	DeviceIDSet   bool
	DeviceID      pgtype.UUID
	RecordedAtSet bool
	RecordedAt    pgtype.Timestamptz
	TimeOffsetSec *int32
	DisplayName   *string
	ID            pgtype.UUID
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo,
		arg.SessionIDSet,
		arg.SessionID,
		arg.TournamentID,
		arg.DeviceIDSet,
		arg.DeviceID,
		arg.RecordedAtSet,
		arg.RecordedAt,
		arg.TimeOffsetSec,
		arg.DisplayName,
		arg.ID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DeviceID,
		&i.UploaderID,
		&i.StorageKey,
		&i.RecordedAt,
		&i.DurationSec,
		&i.TimeOffsetSec,
		&i.CreatedAt,
		&i.ThumbnailKey,
		&i.DisplayName,
		&i.HlsMasterKey,
		&i.HLSStatus,
		&i.SourceVideoCodec,
		&i.SourceAudioCodec,
		&i.SourceWidth,
		&i.SourceHeight,
		&i.PassthroughOk,
		&i.TournamentID,
	)
	return i, err
}

const updateVideoHLSReady = `-- name: UpdateVideoHLSReady :execrows
UPDATE videos
SET hls_status = 'ready', hls_master_key = $1::text
WHERE id = $2::uuid
`

type UpdateVideoHLSReadyParams struct {
	HlsMasterKey string
	ID           pgtype.UUID
}

func (q *Queries) UpdateVideoHLSReady(ctx context.Context, arg UpdateVideoHLSReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVideoHLSReady, arg.HlsMasterKey, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVideoHLSStatus = `-- name: UpdateVideoHLSStatus :execrows
UPDATE videos
SET hls_status = $1::hls_status
WHERE id = $2::uuid
`

type UpdateVideoHLSStatusParams struct {
	HLSStatus HLSStatus
	ID        pgtype.UUID
}

func (q *Queries) UpdateVideoHLSStatus(ctx context.Context, arg UpdateVideoHLSStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVideoHLSStatus, arg.HLSStatus, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVideoProbe = `-- name: UpdateVideoProbe :one
UPDATE videos
SET
  recorded_at = CASE WHEN $1::bool THEN $2::timestamptz ELSE recorded_at END,
  duration_sec = CASE WHEN $3::bool THEN $4::int ELSE duration_sec END
WHERE id = $5
RETURNING id, session_id, device_id, uploader_id, storage_key, recorded_at, duration_sec, time_offset_sec, created_at, thumbnail_key, display_name, hls_master_key, hls_status, source_video_codec, source_audio_codec, source_width, source_height, passthrough_ok, tournament_id
`

type UpdateVideoProbeParams struct {
	RecordedAtSet  bool
	RecordedAt     pgtype.Timestamptz
	DurationSecSet bool
	DurationSec    *int32
	ID             pgtype.UUID
}

func (q *Queries) UpdateVideoProbe(ctx context.Context, arg UpdateVideoProbeParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideoProbe,
		arg.RecordedAtSet,
		arg.RecordedAt,
		arg.DurationSecSet,
		arg.DurationSec,
		arg.ID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DeviceID,
		&i.UploaderID,
		&i.StorageKey,
		&i.RecordedAt,
		&i.DurationSec,
		&i.TimeOffsetSec,
		&i.CreatedAt,
		&i.ThumbnailKey,
		&i.DisplayName,
		&i.HlsMasterKey,
		&i.HLSStatus,
		&i.SourceVideoCodec,
		&i.SourceAudioCodec,
		&i.SourceWidth,
		&i.SourceHeight,
		&i.PassthroughOk,
		&i.TournamentID,
	)
	return i, err
}

const updateVideoSource = `-- name: UpdateVideoSource :execrows
UPDATE videos
SET
  source_video_codec = $1::text,
  source_audio_codec = $2::text,
  source_width       = $3::int,
  source_height      = $4::int,
  passthrough_ok     = $5::bool
WHERE id = $6::uuid
`

type UpdateVideoSourceParams struct {
	SourceVideoCodec *string
	SourceAudioCodec *string
	SourceWidth      *int32
	SourceHeight     *int32
	PassthroughOk    bool
	ID               pgtype.UUID
}

func (q *Queries) UpdateVideoSource(ctx context.Context, arg UpdateVideoSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVideoSource,
		arg.SourceVideoCodec,
		arg.SourceAudioCodec,
		arg.SourceWidth,
		arg.SourceHeight,
		arg.PassthroughOk,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVideoThumbnail = `-- name: UpdateVideoThumbnail :execrows
UPDATE videos
SET thumbnail_key = $2
WHERE id = $1
`

type UpdateVideoThumbnailParams struct {
	ID           pgtype.UUID
	ThumbnailKey *string
}

func (q *Queries) UpdateVideoThumbnail(ctx context.Context, arg UpdateVideoThumbnailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVideoThumbnail, arg.ID, arg.ThumbnailKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
